### PR TITLE
add(feat): add list of map elements in summary

### LINKED ISSUE #116: Add basemaps and layers lists in summary
Add just the basemaps and layers names, not the entire hierarchy.

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Before: basemaps, layers, tileSchemas, extentSets and lodSets are not
listed in the summary
After: add lists for basemaps, layers, tileSchemas, extentSets and
lodSets in the summary
Element validitidy state is not set for the moment.

Closes #116

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/143)

### CODE REVIEW

**Comment by jolevesq** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[.eslintrc.yml, line 167 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143#-L3EkuKceURx2gaWFwHm:-L3EkuKceURx2gaWFwHn:b-vztmuw) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/10c0e1cb91abb075adbad5f3333483eb0125760a/.eslintrc.yml#L167)):*
> ```YAML
>   max-nested-callbacks: 0
>   max-params: 0
>   max-statements: [2, 50]
> ```

We should't change this setting. We should try to break the code in smaller pieces to avoid the error 

---

*[src/app/core/modelManager.service.js, line 279 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143#-L3ElDUA517bs8C3i-In:-L3ElDUA517bs8C3i-Io:b-jeh98m) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/10c0e1cb91abb075adbad5f3333483eb0125760a/src/app/core/modelManager.service.js#L279)):*
> ```JavaScript
> 
>         for (let i of setNames) {
>             // const mapItems = model.baseMaps;
> ```

Can you remove comments

---

*[src/app/core/modelManager.service.js, line 285 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143#-L3ElGpedu4NRi9z6qNs:-L3ElGpedu4NRi9z6qNt:b-jeh98m) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/10c0e1cb91abb075adbad5f3333483eb0125760a/src/app/core/modelManager.service.js#L285)):*
> ```JavaScript
> 
>             for (let [j, item] of items.entries()) {
>                 // const validState = getValidityValue('baseMaps', i, arrKeys);
> ```

Can you remove comments

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143)*

**Comment by ChrisLatRNCan** [comment]
*[.eslintrc.yml, line 167 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143#-L3EkuKceURx2gaWFwHm:-L3EmCHPyD5keFJJ_FOn:bobjk8n) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/10c0e1cb91abb075adbad5f3333483eb0125760a/.eslintrc.yml#L167)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should't change this setting. We should try to break the code in smaller pieces to avoid the error 
</blockquote></details>

see my email on modelManager/stateManager. I'll reverse the value to 30 with a another issue about the implementation of a stateManager.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 285 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143#-L3ElGpedu4NRi9z6qNs:-L3EnbMTQ9biwKhjJ3L8:b-2cttiz) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/10c0e1cb91abb075adbad5f3333483eb0125760a/src/app/core/modelManager.service.js#L285)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you remove comments
</blockquote></details>

I'll keep it there. It helps me to remember where to call my function to get validity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 279 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143#-L3ElDUA517bs8C3i-In:-L3EnxUxiGezfktVkx5i:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/10c0e1cb91abb075adbad5f3333483eb0125760a/src/app/core/modelManager.service.js#L279)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you remove comments
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143)*

**Comment by jolevesq** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/core/modelManager.service.js, line 285 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143#-L3ElGpedu4NRi9z6qNs:-L3EtR8w4tEkEOkkmD0N:blmrowb) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/10c0e1cb91abb075adbad5f3333483eb0125760a/src/app/core/modelManager.service.js#L285)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

I'll keep it there. It helps me to remember where to call my function to get validity
</blockquote></details>

Can you put info so we know it is not garbage

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 285 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143#-L3ElGpedu4NRi9z6qNs:-L3EtfLi_myJ-gF8zDex:b-xwx5x2) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/10c0e1cb91abb075adbad5f3333483eb0125760a/src/app/core/modelManager.service.js#L285)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put info so we know it is not garbage
</blockquote></details>

sure .Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/143#-:-L3EudO90-WRwFTCMJ88:bnfp4nl)*

**Pull request merged**
