### PR TITLE
fix(slider): fix CSS, null array and converter years

### LINKED ISSUE #567: Date to milliseconds converter problem
The CSS foe the date picker is not included inside the code. Plus, the date starts at 2010. Make this start in the early 1900.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #567

## Testing

https://jolevesq.github.io/fgpa-apgf/samples/fgpv-author.html

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/568)

### CODE REVIEW

**Comment by aparujan** [comment]
___
*[src/content/styles/main.scss, line 15 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/568#-MKfdGCoE0w6jy37jjiR:-MKfdGCoE0w6jy37jjiS:b7f6xqh) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/bf3e9e8807f22ba89a51e7e8d28587b40e19a084/src/content/styles/main.scss#L15)):*
> ```SCSS
> }
> 
> // Picker is created outside fgpa div, import separatly
> ```

separately   <-- spelling

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/568)* status: all files reviewed, 1 unresolved discussion (waiting on @aparujan)

___
*[src/content/styles/main.scss, line 15 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/568#-MKfdGCoE0w6jy37jjiR:-MKfea_A7c7h_fHLYb8Z:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/bf3e9e8807f22ba89a51e7e8d28587b40e19a084/src/content/styles/main.scss#L15)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

separately   <-- spelling
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 9 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/568#-:-MP9ufUXCmlOWIHBMlhx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aparujan)

**Review by jolevesq — COMMENTED** [review]
> Dismissed @aparujan from a discussion.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/568)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
