### PR TITLE
jsdoc(core) add missing jsdoc

### LINKED ISSUE #205: Add missing JSDOC documentation for core

### PR DESCRIPTION
**Pull request by Pewillia**
closes #205

## Checklist

- [X] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [X] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/core/common.service.js, line 20 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbCIyDuJbLjkULiHV:-L9KbCIyDuJbLjkULiHW:b-dv1dz3) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/common.service.js#L20)):*
> ```JavaScript
>  * @param {Object} $timeout promise with timeout Angular object
>  * @param {Object} constants  modules that contain all the constants
>  * @return {Object} service  Angular object
> ```

Itis not an Angular object, it is the common service

---

*[src/app/core/core-loader.js, line 6 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbHVr9_fQoEPOgAJi:-L9KbHVr9_fQoEPOgAJj:bsrwopa) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/core-loader.js#L6)):*
> ```JavaScript
>  * @module app.core
>  *
>  * @description import required common services
> ```

not only for common but for all core services

---

*[src/app/core/debounce.service.js, line 12 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbQOt6RlYPUzu3cSS:-L9KbQOt6RlYPUzu3cST:b-68air0) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/debounce.service.js#L12)):*
> ```JavaScript
>     .factory('debounceService', debounceService);
> 
> /** Registers a function for debouncing. If the returned function is executed more than once at intervals less that the detection period, only the first call will go through.
> ```

/**
* ... description

---

*[src/app/core/debounce.service.js, line 17 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbWu0ClL93NPrF7HW:-L9KbWu0ClL93NPrF7HX:b-wo5tus) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/debounce.service.js#L17)):*
> ```JavaScript
> * @param {Object} $timeout promise with timeout Angular object
> * @param {Object} $q promise Angular object
> * @return {Object} service Angular object
> ```

Not Angualr, it is the debounce service

---

*[src/app/core/external.service.js, line 20 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbgAF6A3L-A49k9_O:-L9KbgAF6A3L-A49k9_P:b-sbhsqb) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/external.service.js#L20)):*
> ```JavaScript
>  * @param  {Object} translations translation object that contains one property for every language Angular object
>  * @param  {Object} $translate translate service Angular Object
>  * @return {Object} service Angular object
> ```

... return the service

---

*[src/app/core/external.service.js, line 50 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kbk4T-QrhIm_ovL-d:-L9Kbk4UBkDUGf_9AGRq:b6ve2t) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/external.service.js#L50)):*
> ```JavaScript
> 
>         /**
>          * @function extensionDialogController
> ```

Add description: It is the extension dialog controller

---

*[src/app/core/modelManager.service.js, line 16 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kbs7Q7bxnNyVkLVLO:-L9Kbs7Q7bxnNyVkLVLP:b-35wr9) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/modelManager.service.js#L16)):*
> ```JavaScript
> 
> /**
>  * @function modelmanager
> ```

Add description: Service who manage the model use by Angular Schema Form

---

*[src/app/core/modelManager.service.js, line 22 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kc0C09kEima3zo7Lw:-L9Kc0C09kEima3zo7Lx:bqeube3) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/modelManager.service.js#L22)):*
> ```JavaScript
>  * @param {Object} constants  javascript methods that are to be common
>  * @param {Object} commonService  service that defines common Javascript methods
>  * @return {Object} service Angular Object
> ```

Not Angular, the model service

---

*[src/app/core/recursion.service.js, line 16 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kc5lU6KuKM3tJSTHG:-L9Kc5lU6KuKM3tJSTHH:b-g46zd0) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/recursion.service.js#L16)):*
> ```JavaScript
>  * @function recursionService
>  * @param {Object} $compile compile html to template Angular object
>  * @returns {Object}  service Angular object
> ```

Not Angular, the recrursion service

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274)*

**Comment by Pewillia** [comment]
Review status: 0 of 6 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/app/core/common.service.js, line 20 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbCIyDuJbLjkULiHV:-L9pALKi0j3qjaF3I_KJ:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/common.service.js#L20)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Itis not an Angular object, it is the common service
</blockquote></details>

Done.

---

*[src/app/core/core-loader.js, line 6 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbHVr9_fQoEPOgAJi:-L9pBM6D2507c-U1jsUg:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/core-loader.js#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

not only for common but for all core services
</blockquote></details>

Done.

---

*[src/app/core/debounce.service.js, line 12 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbQOt6RlYPUzu3cSS:-L9pCJBH2NRGGn4oPJGX:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/debounce.service.js#L12)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

/**
* ... description
</blockquote></details>

Done.

---

*[src/app/core/debounce.service.js, line 17 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbWu0ClL93NPrF7HW:-L9pCPT9BnWp_aTDDu5W:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/debounce.service.js#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not Angualr, it is the debounce service
</blockquote></details>

Done.

---

*[src/app/core/external.service.js, line 20 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbgAF6A3L-A49k9_O:-L9q7IPT9hTV4qrqLUQr:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/external.service.js#L20)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

... return the service
</blockquote></details>

Done.

---

*[src/app/core/external.service.js, line 50 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kbk4T-QrhIm_ovL-d:-L9q8xKw-spn36bPic7x:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/external.service.js#L50)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add description: It is the extension dialog controller
</blockquote></details>

Done.

---

*[src/app/core/modelManager.service.js, line 16 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kbs7Q7bxnNyVkLVLO:-L9q8qbC-6bBv02eLBqK:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/modelManager.service.js#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add description: Service who manage the model use by Angular Schema Form
</blockquote></details>

Done.

---

*[src/app/core/modelManager.service.js, line 22 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kc0C09kEima3zo7Lw:-L9q8hLC5l78YB8Ea22_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/modelManager.service.js#L22)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not Angular, the model service
</blockquote></details>

Done.

---

*[src/app/core/recursion.service.js, line 16 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kc5lU6KuKM3tJSTHG:-L9q9unB5xGuWR5au02w:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/recursion.service.js#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not Angular, the recrursion service
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274)*

**Comment by jolevesq** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274)*

**Comment by Pewillia** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/app/core/external.service.js, line 20 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9KbgAF6A3L-A49k9_O:-L9qFHqx7k1LJjwmaBpH:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/external.service.js#L20)):*
<details><summary><i>Previously, Pewillia wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[src/app/core/external.service.js, line 50 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kbk4T-QrhIm_ovL-d:-L9qFJ6y5B_YZolNLzk7:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/external.service.js#L50)):*
<details><summary><i>Previously, Pewillia wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[src/app/core/modelManager.service.js, line 16 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kbs7Q7bxnNyVkLVLO:-L9qFJnQDhMo30UIItVL:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/modelManager.service.js#L16)):*
<details><summary><i>Previously, Pewillia wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[src/app/core/modelManager.service.js, line 22 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kc0C09kEima3zo7Lw:-L9qFKaQ7tXNvw10osB_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/modelManager.service.js#L22)):*
<details><summary><i>Previously, Pewillia wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[src/app/core/recursion.service.js, line 16 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-L9Kc5lU6KuKM3tJSTHG:-L9qFLnf329xRCt8I0ar:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/60e52fb5de73553500e8c035d44f98e72e6950ef/src/app/core/recursion.service.js#L16)):*
<details><summary><i>Previously, Pewillia wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274)*

**Comment by jolevesq** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-:-L9qFQb23rQP_4h2CZcp:bnfp4nl)*

**Comment by jolevesq** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/274#-:-L9qFXKkAIQiElL096-P:bnfp4nl)*

**Pull request merged**
