### PR TITLE
add(summary): sub-tab link

### LINKED ISSUE #134: Create hyperlink from map legend section to go to ui legend section
Make a link to easily navigate between both legend section from ui and map.

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Add hyperlinks between summary and sub-tab
Add hyperlinks between layers and basemaps with their corresponding section in the form
Add hyperlinks between map legend section and ui legend section

Closes #134,#164,#182

## Testing
Chrome and Firefox

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/183)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/core/common.service.js, line 193 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183#-L4w-kj8HNW1GxIHe4SI:-L4w-kj8HNW1GxIHe4SJ:bb752ax) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/5a439ecccbc0f550bbc65f63ba85d0c849bfc6d0/src/app/core/common.service.js#L193)):*
> ```JavaScript
> 
>     /**
>      * Get the current array of languags.
> ```

Typo

---

*[src/app/core/constant.service.js, line 46 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183#-L4w-sg9rcdjAp_GzF-v:-L4w-sg9rcdjAp_GzF-w:b5z9034) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/5a439ecccbc0f550bbc65f63ba85d0c849bfc6d0/src/app/core/constant.service.js#L46)):*
> ```JavaScript
>                 keys: ['form.service.urls', 'search', 'export']
>             }
>         }
> ```

Can you add a TODO note like above to say to add new tab to those constants

---

*[src/app/core/core.run.js, line 151 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183#-L4w066JdugNbHQ25m9Q:-L4w066JdugNbHQ25m9R:b-ekr7wv) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/5a439ecccbc0f550bbc65f63ba85d0c849bfc6d0/src/app/core/core.run.js#L151)):*
> ```JavaScript
>         }
>     }, 1000);
> }
> ```

Can you put this peace of code and the next function inside the summary directive instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183)*

**Comment by jolevesq** [comment]
In French there is a problem, icon are missing. Will you solve this inside this PR?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183#-:-L4w1OQyxY0BMQlU9cnt:bmlreym)*

**Comment by ChrisLatRNCan** [comment]
It is when we are switching language. I can do it in the same PR. Issue #182 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183#-:-L4w1yy8xrSUJxHYY9wd:b3mq1jg)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/common.service.js, line 193 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183#-L4w-kj8HNW1GxIHe4SI:-L4w2cYsQ1bWQobCgFh9:bkhv6vo) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/5a439ecccbc0f550bbc65f63ba85d0c849bfc6d0/src/app/core/common.service.js#L193)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

It's more then a typo it's the wrong description. To much cut and paste.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/core.run.js, line 151 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183#-L4w066JdugNbHQ25m9Q:-L4w3X1OMV3pl8nyE-3e:bm4cjzp) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/5a439ecccbc0f550bbc65f63ba85d0c849bfc6d0/src/app/core/core.run.js#L151)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put this peace of code and the next function inside the summary directive instead?
</blockquote></details>

OK, I'll try that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/summary/summary.directive.js, line 184 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183#-L5ESCNHyzAYr4K_hEN6:-L5ESCNHyzAYr4K_hEN7:b-y8r5ob) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/4491fb9bfec634f3425770df687911045aca533b/src/app/ui/summary/summary.directive.js#L184)):*
> ```JavaScript
>                 const childrenPane = Array.from(elPane[constants.subTabs[section].index].children);
> 
>                 if (childrenTab.length === constants.subTabs[section].keys.length) {
> ```

The code is duplicate. It will never hit the second if?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183#-:-L5ERgKiy60z6jLLOacR:bnfp4nl)*

**Comment by jolevesq** [comment]
Reviewed 2 of 3 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183)*

**Comment by jolevesq** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/183)*

**Pull request merged**
