### PR TITLE
feat(legend): Add snippet of config to create 4 legend groups

### LINKED ISSUE #180: Add button to add snippet of code for legend type
While we are waiting for a real ui legend, let user add snippet of json for the different type.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #180

## Testing

Chrome

## Documentation

Inline

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/187)

### CODE REVIEW

**Comment by ChrisLatRNCan** [comment]
Have that content with config-authorB
"\"{\\\"name\\\": \\\"root\\\", \\\"children\\\": []}\""  and the JSON validation process says it is good. However, the buttons to add snippet work well.


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/187#-:-L5K5KPFA6FrQ_Hsesnl:b-c2owh5)*

**Comment by jolevesq** [comment]
Good catch. Solved now.

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/187#-:-L5Kih7P3Np-0IPultnV:b-77pgkc)*

**Comment by ChrisLatRNCan** [comment]
We should not see the editor since we it is autopopulate (config-full)



---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/187#-:-L5Kjw0HzXM7S1LQTMM2:bmfpypu)*

**Comment by jolevesq** [comment]
Set hidden by default so now it will only show when structured.

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/187#-:-L5Kmgbe6rnrFG7u7qGu:bd7gl3s)*

**Comment by ChrisLatRNCan** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/187#-:-L5KnXWP0NiQqZb5myYO:bnfp4nl)*

**Pull request merged**
