### PR TITLE
fix(header): Solve issue with save and make the save name increment a…

### LINKED ISSUE #291: Error when save and JSON not valid
If there is an error in JSON legend and we try to save there is an error. We should instead show a message to user to inform him the file is not valid

### PR DESCRIPTION
**Pull request by jolevesq**
…utomatically

Closes #291

## Testing

Chrome

## Documentation

Yes

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/310)

### CODE REVIEW

**Comment by ChrisLatRNCan** [comment]
Increment works well but  as #291 is saying, do we want a buggy structured legend to be saved. I think you already talked  about it to me but I don't remember what has been decided.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/310#-:-LAmg2ZeD7aY7LbT4b6a:bnlwd8p)*

**Comment by jolevesq** [comment]
You are right, I missed this part. Will do an update to solve bad legend issue. I will show a message inside the save window to say we can't save.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/310#-:-LArhPQ852MdHf7sAOfs:b-oqii7j)*

**Comment by ChrisLatRNCan** [comment]
When there is a JSON error I see a message but not when there's a bad id.

---







*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/310#-:-LAs8EB-ETbNhLv2nB0y:b2g91vn)*

**Comment by ChrisLatRNCan** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/310)*

**Pull request merged**
