### PR TITLE
fix(form): dynamic select choice doesn't copyValueTo for array

### LINKED ISSUE #178: Changing layer type in select box doesn't update layers[].layerType
When I change layer type choice from one type another, in the model, layers[].layerType is not updated properly even if the condition to show/hide the layers definition works.

For the moment, user can only create esriDynamic type of layer

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #178

## Testing

Chrome

## Documentation

Inline

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/185)

### CODE REVIEW

**Comment by ChrisLatRNCan** [comment]
The deploy works well

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/forms/form.service.js, line 187 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-L5F8MsBdezy6k7e2YKX:-L5F8MsCPEorcAMBpaoZ:b-lscu8g) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cadb825fbb718ac642c58fe393b01f5ac1466df/src/app/ui/forms/form.service.js#L187)):*
> ```JavaScript
>         const itemLink = item.targetLink.split('.');
> 
>         // get active element to retrieve targetParent (loop trought parent element to find the target)
> ```

throught instead of trought

---

*[src/app/ui/forms/form.service.js, line 265 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-L5F9DiQAncqdd79zfQL:-L5F9DiQAncqdd79zfQM:bbdpzvd) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cadb825fbb718ac642c58fe393b01f5ac1466df/src/app/ui/forms/form.service.js#L265)):*
> ```JavaScript
>         for (let key of item.targetElement) {
>             update = commonService.isArray(update[key]) ? update[key][index] :
>                 (typeof update[key] === 'object') ? update[key] : update[key] = modelValue;
> ```

We can do an assignation inside ?: operator ?

---

*[src/app/ui/forms/map/map.directive.js, line 460 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-L5F9YIXBhqQ3KrQJShE:-L5F9YIXBhqQ3KrQJShF:b-hqyasv) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cadb825fbb718ac642c58fe393b01f5ac1466df/src/app/ui/forms/map/map.directive.js#L460)):*
> ```JavaScript
>                         { 'type': 'fieldset', 'htmlClass': 'av-accordion-toggle av-layer', 'title': $translate.instant('form.map.layer'), 'items': [
>                             { 'key': 'layers[]', 'htmlClass': `av-accordion-content`, 'notitle': true, 'items': [
>                                 { 'key': 'layers[].layerChoice', 'type': 'select', 'targetElement': ['layers', 'layerType'], 'targetParent': 'av-accordion-content', 'onChange': (model, item) => { self.formService.copyValueToModelIndex(model, item, $scope.model); } },
> ```

Not sure but I think you can remove a pair of braces in (model, item) => self.formService.copyValueToModelIndex(model, item, $scope.model); 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-:-L5FA3khXjK939lV39ag:bl9vmoh)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/forms/form.service.js, line 187 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-L5F8MsBdezy6k7e2YKX:-L5FEhIatMrZQnnsQOyi:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cadb825fbb718ac642c58fe393b01f5ac1466df/src/app/ui/forms/form.service.js#L187)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

throught instead of trought
</blockquote></details>

Done.

---

*[src/app/ui/forms/form.service.js, line 265 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-L5F9DiQAncqdd79zfQL:-L5FAMquYS-9W1-9Qlr7:b-r9o7v7) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cadb825fbb718ac642c58fe393b01f5ac1466df/src/app/ui/forms/form.service.js#L265)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

We can do an assignation inside ?: operator ?
</blockquote></details>

Yep. Don't know if it should be avoid but it works

---

*[src/app/ui/forms/map/map.directive.js, line 460 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-L5F9YIXBhqQ3KrQJShE:-L5FEgEk85-ui-tDqoE2:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cadb825fbb718ac642c58fe393b01f5ac1466df/src/app/ui/forms/map/map.directive.js#L460)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Not sure but I think you can remove a pair of braces in (model, item) => self.formService.copyValueToModelIndex(model, item, $scope.model); 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185)*

**Comment by ChrisLatRNCan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/forms/form.service.js, line 187 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-L5F8MsBdezy6k7e2YKX:-L5FFCV_FVDU9xytZav7:bmcw22e) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cadb825fbb718ac642c58fe393b01f5ac1466df/src/app/ui/forms/form.service.js#L187)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

trought still there

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/forms/form.service.js, line 187 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-L5F8MsBdezy6k7e2YKX:-L5FH8GBx2aHGUc62VZP:b-kumf8p) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cadb825fbb718ac642c58fe393b01f5ac1466df/src/app/ui/forms/form.service.js#L187)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

trought still there
</blockquote></details>

Corrected wrong one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185)*

**Comment by jolevesq** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/forms/form.service.js, line 187 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-L5F8MsBdezy6k7e2YKX:-L5FHCNIC8AVhBkEI0fl:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cadb825fbb718ac642c58fe393b01f5ac1466df/src/app/ui/forms/form.service.js#L187)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Corrected wrong one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185)*

**Comment by ChrisLatRNCan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/ui/forms/form.service.js, line 187 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-L5F8MsBdezy6k7e2YKX:-L5FI5TixDnLCV0Ys_MQ:bb6scen) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cadb825fbb718ac642c58fe393b01f5ac1466df/src/app/ui/forms/form.service.js#L187)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

C BO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185)*

**Comment by ChrisLatRNCan** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185#-:-L5FIa7XkX0VSmbOyg3m:bnfp4nl)*

**Comment by ChrisLatRNCan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/185)*

**Pull request merged**
