### PR TITLE
refactor(core): create stateManager service

### LINKED ISSUE #145: create stateManager
Actually state model is managed in the modelManager. As it goes bigger, modelManager needs to be splitted in two entities: modelManager (model and schema) and stateManager (state).
With this change the eslint parameter for max statement needs to be put back to his original value (30)

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Before: error creation by ESLint because the modelManager has to many statements.
Solution: divide modelManager into two entities: modelManager for schema and model and stateManager for state.

Closes #145

## Testing
Test with Chrome

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/149)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/stateManager.service.js, line 201 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/149#-L3TPMOOwSA6LLdLawNu:-L3TPMOOwSA6LLdLawNv:b5szsd5) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/7bb6f15c005ffe5521fe86f6bce5e0b54b885057/src/app/core/stateManager.service.js#L201)):*
> ```JavaScript
> 
>         customTitles[modelName].forEach(title => {
>             if (stateModel.hasOwnProperty('key') && stateModel.key === title){
> ```

Space before {

---

*[src/app/core/stateManager.service.js, line 299 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/149#-L3TP_i3GYiINhISc4tM:-L3TP_i3GYiINhISc4tN:b52exes) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/7bb6f15c005ffe5521fe86f6bce5e0b54b885057/src/app/core/stateManager.service.js#L299)):*
> ```JavaScript
>         });
> 
>         // Add specifis keys so the missing tabs can be represented in the summary
> ```

Typo in comment specific instead of specifis

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/149)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/stateManager.service.js, line 201 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/149#-L3TPMOOwSA6LLdLawNu:-L3TQXneQrTCRDmj_g8y:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/7bb6f15c005ffe5521fe86f6bce5e0b54b885057/src/app/core/stateManager.service.js#L201)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space before {
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/149)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/stateManager.service.js, line 299 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/149#-L3TP_i3GYiINhISc4tM:-L3TQZ1mSkl8oodxN8KK:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/7bb6f15c005ffe5521fe86f6bce5e0b54b885057/src/app/core/stateManager.service.js#L299)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo in comment specific instead of specifis
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/149)*

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/149)*

**Comment by jolevesq** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/149#-:-L3TVHQHLklizL381Dir:bnfp4nl)*

**Pull request merged**
