### PR TITLE
add(core): add validation process for map and spatial items

### LINKED ISSUE #167: Add required element in schema for layers and basemaps
Actually, id and URL properties of layers and basemaps are not required. Consequently, the validation process doesn't generate an error when there's nothing for those properties. So add required keyword at proper places in the schema.

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Before: some empty tileSchemas, extents, lods, layers and basemaps
mandatory parameters are not detected by validation process.
Also, missing title in summary when id or name parameters are empty
Missing overall validation for tileSchemas, extents, lods, layers and basemaps

After: add corresponding require in schemas map.[lang].json.
Add special title for the summary if one is missing.
Add global validation for tileSchemas, extents, lods, layers and basemaps

Closes #167,#179

## Testing
Chrome

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/190)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/core/constant.service.js, line 24 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-L5QBfdyWhJDDkjSjp-H:-L5QBfdyWhJDDkjSjp-I:b-8fpxvx) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/71112b1ba721f9b49eaee0691b2830a2e6a4a139/src/app/core/constant.service.js#L24)):*
> ```JavaScript
>         delayEventSplash: 750,
>         delayUpdateColumns: 1000,
>         delaySetSubTab: 5000,
> ```

5 second, it start to be a lot. Can you do $interval to check at every second if the tag exist?

---

*[src/app/core/stateManager.service.js, line 384 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-L5QC1E1R6z_X9W7_Ofb:-L5QC1E1R6z_X9W7_Ofc:bw84u0h) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/71112b1ba721f9b49eaee0691b2830a2e6a4a139/src/app/core/stateManager.service.js#L384)):*
> ```JavaScript
>                     title = $translate.instant('summary.missing.name');
>                     stype = 'bad-element';
>                     //valid = false;
> ```

Do we need this line?

---

*[src/app/core/stateManager.service.js, line 539 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-L5QC4agLu1rK6WKbAsr:-L5QC4agLu1rK6WKbAss:bepf54z) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/71112b1ba721f9b49eaee0691b2830a2e6a4a139/src/app/core/stateManager.service.js#L539)):*
> ```JavaScript
>                 // remove first element of keys set if it is '0'
>                 if (keys [0] === '0') keys.shift();
>                 //second time for extents
> ```

space after //

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190)*

**Comment by ChrisLatRNCan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/app/core/constant.service.js, line 24 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-L5QBfdyWhJDDkjSjp-H:-L5QDjLL_mqPZqAOMpxN:b-ppp3x3) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/71112b1ba721f9b49eaee0691b2830a2e6a4a139/src/app/core/constant.service.js#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

5 second, it start to be a lot. Can you do $interval to check at every second if the tag exist?
</blockquote></details>

I'll try that

---

*[src/app/core/stateManager.service.js, line 384 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-L5QC1E1R6z_X9W7_Ofb:-L5QDE939WZs6thu95e3:b-qsu0nf) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/71112b1ba721f9b49eaee0691b2830a2e6a4a139/src/app/core/stateManager.service.js#L384)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need this line?
</blockquote></details>

I put it back, so I'll be sure I won't miss anything. 

---

*[src/app/core/stateManager.service.js, line 539 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-L5QC4agLu1rK6WKbAsr:-L5QDi6kSnrmxRL91oy-:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/71112b1ba721f9b49eaee0691b2830a2e6a4a139/src/app/core/stateManager.service.js#L539)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

space after //
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190)*

**Comment by jolevesq** [comment]
Have you an idea why it took 15 seconds to process the config-full file?

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/app/ui/summary/summary.directive.js, line 178 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-L5Te7cZAmL8y44kBxHb:-L5Te7cZAmL8y44kBxHc:b-g4i73h) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/31312c3092476c47c319a333faeeb16a5e13fa75/src/app/ui/summary/summary.directive.js#L178)):*
> ```JavaScript
>  */
>     function setSubTab(constants) {
>         $timeout(() => {
> ```

Why does your interval is inside a timeout? You should use $interval instead of setInterval.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-:-L5TeVL_M_oLGQjVhf9Y:b-6t7nhd)*

**Comment by ChrisLatRNCan** [comment]
I'll look at the profiler

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-:-L5UEFAJC7wUnHgU1QYe:bxofukh)*

**Comment by ChrisLatRNCan** [comment]
So I ran the profiler without setting the subTab and it doesn't have much impact on the overall loading time.

It seems to take a lot of time in $apply and completeOutstanding request

image
image
image

**Comment by jolevesq** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-:-L5UtQ1ummpjHbn0sw-O:bnfp4nl)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/summary/summary.directive.js, line 178 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-L5Te7cZAmL8y44kBxHb:-L5UuExUdHD8xvvQKdkC:bry91xs) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/31312c3092476c47c319a333faeeb16a5e13fa75/src/app/ui/summary/summary.directive.js#L178)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why does your interval is inside a timeout? You should use $interval instead of setInterval.
</blockquote></details>

setInterval without the timeout doesn't work. I didn't know about $interval. I'll do the modif. Thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/summary/summary.directive.js, line 178 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190#-L5Te7cZAmL8y44kBxHb:-L5UwMtprfVRABJV5wUN:bnxnc3d) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/31312c3092476c47c319a333faeeb16a5e13fa75/src/app/ui/summary/summary.directive.js#L178)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

setInterval without the timeout doesn't work. I didn't know about $interval. I'll do the modif. Thx
</blockquote></details>

$interval works but just inside a $timeout like setInterval

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190)*

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/190)*

**Pull request merged**
