### PR TITLE
add(schema): upgrade to version 2.4

### LINKED ISSUE #330: Update to schema version 2.4
Update schema to to version 2.4 of the viewer

- Add altText to attribution logo value (related to #280, https://github.com/fgpv-vpgf/fgpv-vpgf/issues/2695)

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
-Schemas update to 2.4;
-Config update to 2.4;
-Forms update to 2.4;
-Add items management for areaOfInterest

Closes #330,#346,#347,#382

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387)

### CODE REVIEW

**Comment by jolevesq** [comment]
Good work! Those are the thing to modify:

* when I set my extent, I loose my title and thumbnail url
* thumbnail url is not required
* when I select version 2.4, it opens in 2.2. Version 2.3 is ok, it opens in 2.3
* for url https://geoappext.nrcan.gc.ca/fgpv/fgpv-2.4.0/dev/rv-main.js, remove the dev part

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed, 7 unresolved discussions (waiting on @ChrisLatRNCan)

---

*[src/app/core/stateManager.service.js, line 502 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBbO6oEdUyfa1-b3LF:-LGBbO6oEdUyfa1-b3LG:btq66kp) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/core/stateManager.service.js#L502)):*
> ```JavaScript
>             .indexOf(`map.[lang].json`) + 1;
> 
>         const setID = [4,'components', 'areaOfInterest'];
> ```

Space after ,

---

*[src/app/core/stateManager.service.js, line 507 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBbSHn2voOIHUcw0YW:-LGBbSHo9okq6hkjIcQp:b7pqtgg) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/core/stateManager.service.js#L507)):*
> ```JavaScript
>         
>         // is there a defined area of interest
>         const found = stateModel.items[4].items.filter((element) => {return element.key === 'areaOfInterest';} );
> ```

No () around single element
Space after { and before }

---

*[src/app/core/stateManager.service.js, line 947 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBbkTM8K_JULUyv4ix:-LGBbkTM8K_JULUyv4iy:b-7rdrxw) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/core/stateManager.service.js#L947)):*
> ```JavaScript
>      * @return {String} id
>      */
>     function setItemId(hlink, elType, elSubType = '', index) {
> ```

Put your optional parameter at the end of parameters list

---

*[src/app/ui/forms/form.service.js, line 49 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBcBSv3mgjid1u7mqw:-LGBcBSw8yRoCU2_5hdr:b4p1flf) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/ui/forms/form.service.js#L49)):*
> ```JavaScript
>         addCustomAccordion,
>         setExtent,
>         setAreaOfInterest,
> ```

Can you reuse the setExtent controller instead of creating a new one?

---

*[src/app/ui/forms/map/map.directive.js, line 1003 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBcpus0RV7W6E1ATck:-LGBcput0utIt4-5P_NQ:byquu61) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/ui/forms/map/map.directive.js#L1003)):*
> ```JavaScript
>                                         self.formService.copyValueToFormIndex(model, item);}, constants.debInput, false)
>                                     },
>                                     // { 'key': 'components.areaOfInterest[].title' },
> ```

Do we need this?

---

*[src/content/samples/config/canada-world-en.json, line 325 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBdEtIDPTMCWq2qzrk:-LGBdEtIDPTMCWq2qzrl:b-2cs85w) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/content/samples/config/canada-world-en.json#L325)):*
> ```JSON
>                 "layerType": "esriFeature",
>                 "url": "https://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBME_CBCE_HS_RO_3978/MapServer",
>                 "opacity": 1
> ```

Combine this layer with CBMT and apply .7 opacity. You can then remove the layer

---

*[src/content/samples/config/canada-world-fr.json, line 322 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBd0s5DCNhMgjRRyl_:-LGBd0s5DCNhMgjRRyla:b-2cs85w) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/content/samples/config/canada-world-fr.json#L322)):*
> ```JSON
>             "altText": "Relief ombragé",
>             "layers": [{
>                 "id": "CBME_CBCE_HS_RO_3978",
> ```

Combine this layer with CBMT and apply .7 opacity. You can then remove the layer

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-:-LGB_jryCKZpfVw5U6j8:b-rqp27p)*

**Comment by ChrisLatRNCan** [comment]
*[src/content/samples/config/canada-world-fr.json, line 322 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBd0s5DCNhMgjRRyl_:-LGBiYBr2WuJzf82wk5l:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/content/samples/config/canada-world-fr.json#L322)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Combine this layer with CBMT and apply .7 opacity. You can then remove the layer
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387)*

**Comment by ChrisLatRNCan** [comment]
*[src/content/samples/config/canada-world-en.json, line 325 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBdEtIDPTMCWq2qzrk:-LGBiE942deRYJwYxOiZ:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/content/samples/config/canada-world-en.json#L325)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Combine this layer with CBMT and apply .7 opacity. You can then remove the layer
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/forms/map/map.directive.js, line 1003 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBcpus0RV7W6E1ATck:-LGBh1zQ0Vigfbl_0jCF:bss4a2b) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/ui/forms/map/map.directive.js#L1003)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/stateManager.service.js, line 947 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBbkTM8K_JULUyv4ix:-LGBgi7E9eTFHf-zcolU:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/core/stateManager.service.js#L947)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put your optional parameter at the end of parameters list
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/stateManager.service.js, line 507 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBbSHn2voOIHUcw0YW:-LGBg5d6CwbXkL253Tco:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/core/stateManager.service.js#L507)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No () around single element
Space after { and before }
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/stateManager.service.js, line 502 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBbO6oEdUyfa1-b3LF:-LGBfxXZ-l-btWk0ngQ0:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/core/stateManager.service.js#L502)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after ,
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387)*

**Comment by ChrisLatRNCan** [comment]
All done

---

Review status: all files reviewed, 7 unresolved discussions (waiting on @jolevesq)

---

*[src/app/ui/forms/form.service.js, line 49 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBcBSv3mgjid1u7mqw:-LGBnjjn3BZCC1MZ1cz-:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/ui/forms/form.service.js#L49)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you reuse the setExtent controller instead of creating a new one?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-:-LGBnmxv98f1cNDpovou:b-4zy5ve)*

**Comment by ChrisLatRNCan** [comment]
___
*[src/app/core/stateManager.service.js, line 507 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/387#-LGBbSHn2voOIHUcw0YW:-LG__gGR0xIG0KMjfXeh:b-3dmbq3) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/ec729128ab6107225df0c92e489768f2f1cda88c/src/app/core/stateManager.service.js#L507)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Still missing spaces
</blockquote></details>

???? où

**Pull request merged**
