### PR TITLE
add(feat): fgpa-schema-splitter integration part 1

### LINKED ISSUE #55: Include fgpa-schema-splitter in fgpa repo
Include [fgpa-schema-splitter](https://github.com/ChrisLatRNCan/fgpa-schema-splitter) in [fgpa-apgf](https://github.com/fgpv-vpgf/fgpa-apgf) repo.
Check first if [fgpa-schema-splitter](https://github.com/ChrisLatRNCan/fgpa-schema-splitter) can be debugged from inside [fgpa-apgf](https://github.com/fgpv-vpgf/fgpa-apgf)

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Add: source file, JSON files, csv files;
Put files at appropriate places in fgpa repo hierachy;
Modify source file to reflect new files localisations;
Modify source file after Linter analysis;
Update Package.json.

Closes #55

## Description
fgpv-vpgf/fgpa-apgf/issues/55

## Testing
Yes, on console

## Documentation
----

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/57)

### CODE REVIEW

**Comment by jolevesq** [comment]
Will need another little demo to understand how it works :smile: 

There is only few syntax error... except that :lgtm: 

---

Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[scripts/genSchemas.js, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57#-Ky281fVfFgnV0n_iqW8:-Ky281fVfFgnV0n_iqW9:btx67u9) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/3de500a484ccb074ac0e92eb422250dd1a38a87c/scripts/genSchemas.js#L10)):*
> ```JavaScript
> const $DotProp = require('dot-prop');
> const $PapaParse = require('papaparse');
> // const deepKeys = require('deep-keys');
> ```

Do we still need this?

---

*[scripts/genSchemas.js, line 152 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57#-Ky27wXnaoL8XC9BHiEj:-Ky27wXnaoL8XC9BHiEk:b-wwal8m) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/3de500a484ccb074ac0e92eb422250dd1a38a87c/scripts/genSchemas.js#L152)):*
> ```JavaScript
> function addLabels(schema, start = '', customPrefix = '') {
>     addTitleLabel(schema[start], '', customPrefix);
>     // addHelpLabel(schema[start]);
> ```

Is it dead code?

---

*[scripts/genSchemas.js, line 187 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57#-Ky27rlj2BQcGq31w3UR:-Ky27rlj2BQcGq31w3US:b64zljn) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/3de500a484ccb074ac0e92eb422250dd1a38a87c/scripts/genSchemas.js#L187)):*
> ```JavaScript
>     let prefix = `${customPrefix}${parent}`;
> 
>     propNames.forEach( prop => {
> ```

Remove space after (

---

*[scripts/genSchemas.js, line 212 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57#-Ky28PKf3hurnHVyqcgf:-Ky28PKf3hurnHVyqcgg:b64zljn) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/3de500a484ccb074ac0e92eb422250dd1a38a87c/scripts/genSchemas.js#L212)):*
> ```JavaScript
>     let prefix = `${customPrefix}${parent}`;
> 
>     propNames.forEach( prop => {
> ```

Remove space after (

---

*[scripts/genSchemas.js, line 406 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57#-Ky28vE79FZLXGQI7vef:-Ky28vE79FZLXGQI7veg:b64zljn) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/3de500a484ccb074ac0e92eb422250dd1a38a87c/scripts/genSchemas.js#L406)):*
> ```JavaScript
>             let enumArray = $DotProp.get(schema, `${prop}.enum`);
>             let newEnum = [];
>             enumArray.forEach( element => {
> ```

Remove space after (

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57#-:-Ky2A-gsQt12FDtkL-5z:b-byj63q)*

**Comment by ChrisLatRNCan** [comment]
*[scripts/genSchemas.js, line 152 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57#-Ky27wXnaoL8XC9BHiEj:-Ky2Al3ac3FJlaj6wtUk:bvzncbw) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/3de500a484ccb074ac0e92eb422250dd1a38a87c/scripts/genSchemas.js#L152)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it dead code?
</blockquote></details>

Until we will be 100 % sure we don't want new help attribute I think we should let it there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57)*

**Comment by ChrisLatRNCan** [comment]
*[scripts/genSchemas.js, line 10 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57#-Ky281fVfFgnV0n_iqW8:-Ky2BoBO_AAy-VbBoyK3:b-y8tqba) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/3de500a484ccb074ac0e92eb422250dd1a38a87c/scripts/genSchemas.js#L10)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we still need this?
</blockquote></details>

I can remove deepKey, I didn't include it in package.json.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57)*

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57)*

**Comment by jolevesq** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/57#-:-Ky2Dd1_gVDt1qFnutrN:bg7igkv)*

**Pull request merged**
