### PR TITLE
fix(ui): summary refactoring

### LINKED ISSUE #71: Summary refactoring
Make the summary reflect the UI interface (tabs, sections, themes, ...) instead of reflecting the schema.
The goal is to improve UX and avoid confusion.

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Before: model based summary with keys as label and no translation
After: form based summary
- Add functions so the modelState could be form generated
- Add titles as lables to summary
- Complete and update translation of translation.csv file
- Complete and update schema translation
- Add missing titles to schemas
- Update form
- Justify left validity symbol in summary
- Trigger summary language change on interface language change
- Change the order in form to keep same order in both form and summary

Closes #71

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/124)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 18 of 22 files at r1.
Review status: 18 of 22 files reviewed at latest revision, 20 unresolved discussions.

---

*[src/app/core/modelManager.service.js, line 219 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Os8Y9WFSlvpvGWvt:-L33Os8Y9WFSlvpvGWvu:b59tat3) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L219)):*
> ```JavaScript
> 
>         // recreate state object used by the summary section
>         // _state[modelName].items = updateSummaryModel([], _model[modelName]);
> ```

Is this still required?

---

*[src/app/core/modelManager.service.js, line 228 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33OvGyOdLCSFdWpMiG:-L33OvGyOdLCSFdWpMiH:b-ggzrnh) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L228)):*
> ```JavaScript
>         // Since map is much more complicated we isolate it
>         if (modelName === 'map') {
>             updateSummaryFormMap(_state[modelName],modelName, cleanForm);
> ```

Space after coma

---

*[src/app/core/modelManager.service.js, line 230 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33OwuTza5vAXjxeXSd:-L33OwuTza5vAXjxeXSe:b-ggzrnh) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L230)):*
> ```JavaScript
>             updateSummaryFormMap(_state[modelName],modelName, cleanForm);
>         } else {
>             updateSummaryForm(_state[modelName],modelName, cleanForm);
> ```

Space after coma

---

*[src/app/core/modelManager.service.js, line 281 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33PF38OXM8youYBfXC:-L33PF38OXM8youYBfXD:btq66km) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L281)):*
> ```JavaScript
>     function setTitle(stateModel, arrForm) {
> 
>         if (stateModel.hasOwnProperty('key') && stateModel.title === ''){
> ```

Space after )

---

*[src/app/core/modelManager.service.js, line 308 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33PQOmqInP3GljuTkj:-L33PQOmqInP3GljuTkk:b-2lp2ek) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L308)):*
> ```JavaScript
>         
>         customTitles[modelName].forEach(title => {
>             if (stateModel.hasOwnProperty('key') && stateModel.key === title){
> ```

Space after ). Looks like setTitle function. Can it be merge with a parameter to specify if it is a title or a custom one?

---

*[src/app/core/modelManager.service.js, line 332 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Pqpgeoo7AVWQ_zV5:-L33Pqpgeoo7AVWQ_zV6:b-1v50bk) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L332)):*
> ```JavaScript
>         arrForm.forEach(item => {
>             if (item.hasOwnProperty('key')) {
>                 if(Array.isArray(item.key)) {
> ```

Space after if

---

*[src/app/core/modelManager.service.js, line 333 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Pt0gfumfdghzky4Q:-L33Pt0gfumfdghzky4R:b-1v50bk) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L333)):*
> ```JavaScript
>             if (item.hasOwnProperty('key')) {
>                 if(Array.isArray(item.key)) {
>                     if(key === item.key[item.key.length - 1]) {
> ```

Space after if

---

*[src/app/core/modelManager.service.js, line 334 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Q0_3UEI4Hz1tWzGy:-L33Q0_3UEI4Hz1tWzGz:b-px1lp4) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L334)):*
> ```JavaScript
>                 if(Array.isArray(item.key)) {
>                     if(key === item.key[item.key.length - 1]) {
>                         itemForm.title =  item.title;
> ```

Too much spaces after =

---

*[src/app/core/modelManager.service.js, line 340 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Q4MzHV4cLTQ2nj1u:-L33Q4MzHV4cLTQ2nj1v:b-1v50bk) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L340)):*
> ```JavaScript
>                 }
>             }
>             if(item.hasOwnProperty('items')) {
> ```

Space after if

---

*[src/app/core/modelManager.service.js, line 387 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33S-nNyKlgzA-UaSHr:-L33S-nNyKlgzA-UaSHs:bvqqq97) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L387)):*
> ```JavaScript
>      * @param {Object} list hidden advance parameters list
>      */
>     function updateSummaryForm(state, modelName, form) {
> ```

Can we merge those 2 functions in one (updatesummary and update summary for map)?

Can we apply the same thing like reduceMap and remove first element even if it does nothing for non map element? Or just run it for map element?

---

*[src/app/core/modelManager.service.js, line 436 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Sc7Cf212cwmL6QXq:-L33Sc7Cf212cwmL6QXr:b-8if5f6) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L436)):*
> ```JavaScript
> 
>                 const valid = [];
>                 for (let i = 0; i < validArr.length; i++) valid.push(validArr[i][0]);
> ```

You can use es6 for loop (for (let a of validArray)

---

*[src/app/core/modelManager.service.js, line 438 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33SmXlb5JwDmgftmfp:-L33SmXlb5JwDmgftmfq:bjjeosy) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L438)):*
> ```JavaScript
>                 for (let i = 0; i < validArr.length; i++) valid.push(validArr[i][0]);
>                 // const reducer = (validState, currValid) => validState && currValid;
>                 // const validState = valid.reduce(reducer);
> ```

Those comments are they needed?

---

*[src/app/core/modelManager.service.js, line 495 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33TYeVjEimjDVFF1bw:-L33TYeVjEimjDVFF1bx:btq66km) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L495)):*
> ```JavaScript
> 
>         const arr = arrKeys.filter(el => el[0].length >= keys.length
>                                         && keys.every((v,i)=> v === el[0][i]));
> ```

Space after )

---

*[src/app/core/modelManager.service.js, line 498 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33TaZM7JQuCcger8B0:-L33TaZM7JQuCcger8B1:b13mz47) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L498)):*
> ```JavaScript
> 
>         const validSet = [];
>         for (let i = 0; i < arr.length; i++) validSet.push(arr[i][1]);
> ```

es6 for loop?

---

*[src/app/core/modelManager.service.js, line 545 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Tu7fi12OiCTGcrOk:-L33Tu7fi12OiCTGcrOl:b-laff5o) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L545)):*
> ```JavaScript
>         const validSet = [];
> 
>         for (let i = 0; i < state.items.length; i++) validSet.push(state.items[i].valid);
> ```

es6 foor loop?

---

*[src/app/core/modelManager.service.js, line 547 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33TwVe9ZQICaHIYBnA:-L33TwVe9ZQICaHIYBnB:b-cibdwv) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L547)):*
> ```JavaScript
>         for (let i = 0; i < state.items.length; i++) validSet.push(state.items[i].valid);
>         // const reducer = (validState, currValid) => validState && currValid;
>         // state.valid = validSet.reduce(reducer);
> ```

Is commented line needed?

---

*[src/app/core/modelManager.service.js, line 552 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33U2rCBdNCUbnOye3Z:-L33U2rCBdNCUbnOye3_:b-jrczfp) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L552)):*
> ```JavaScript
>     }
> 
> //     /**
> ```

Is this function still needed?

---

*[src/app/ui/forms/ui/ui.directive.js, line 73 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Uazg96AGqJSXL-LK:-L33Uazg96AGqJSXL-LL:b-v7z84b) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/ui/forms/ui/ui.directive.js#L73)):*
> ```JavaScript
>     events.$on(events.avValidateForm, () => {
>         $scope.$broadcast('schemaFormValidate');
>         modelManager.validateModel(self.modelName, $scope.activeForm, $scope.form[0].tabs);
> ```

Why do you use form[0].tabs?

---

*[src/app/ui/forms/ui/ui.directive.js, line 139 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33VVRvFCl8PphAutSe:-L33VVRvFCl8PphAutSf:b-qti3kv) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/ui/forms/ui/ui.directive.js#L139)):*
> ```JavaScript
>                 ] },
>                 { 'title': $translate.instant('form.ui.sidemenu'), 'items': [
>                     { 'key': 'logo' },
> ```

You need sideMenu.logo if we look at the schema. Do you modify the schema?

---

*[src/locales/translations.csv, line 46 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33XP5ZTb8lfubuPizK:-L33XP5_T534YfuBA3ya:b-qif6p6) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/locales/translations.csv#L46)):*
> ```CSV
> form.map,form.map.spatialref,Spatial Reference,0,Référence spatiale,0
> form map,form.map.basemaps,Basemaps,0,Cartes de base,0
> form map,form.map.extentset,Spatial Extents Sets,0,"Lots d'étendues spatiales",0
> ```

Why the "

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 219 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Os8Y9WFSlvpvGWvt:-L33uWnFVGC4T-VGC2Aa:b-xvoo8h) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L219)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this still required?
</blockquote></details>

No, I'll remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 219 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Os8Y9WFSlvpvGWvt:-L33uha5zWQ_ggyXvheq:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L219)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

No, I'll remove it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 228 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33OvGyOdLCSFdWpMiG:-L33uq5CO399Aspb4aHE:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L228)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after coma
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 230 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33OwuTza5vAXjxeXSd:-L33ur7T3BiekH57eIrP:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L230)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after coma
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 281 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33PF38OXM8youYBfXC:-L33uxPgCQDsUcIUJmKE:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L281)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after )
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 308 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33PQOmqInP3GljuTkj:-L33vDoUfM35fgp09kNP:baif59l) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L308)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after ). Looks like setTitle function. Can it be merge with a parameter to specify if it is a title or a custom one?
</blockquote></details>

Done for the space. No, they are really two different functions even though they look similar in the structure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 332 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Pqpgeoo7AVWQ_zV5:-L33vrSeZZRegO5sVCt7:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L332)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after if
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 333 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Pt0gfumfdghzky4Q:-L33w-bhlRq-auUfxAV7:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L333)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after if
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 334 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Q0_3UEI4Hz1tWzGy:-L33w4DIQXQZ7NqmJzV-:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L334)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Too much spaces after =
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 340 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Q4MzHV4cLTQ2nj1u:-L33wBVI6SICPviv1chf:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L340)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after if
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 387 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33S-nNyKlgzA-UaSHr:-L33wMgDm6OgIjEAcl_N:b8kfj39) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L387)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we merge those 2 functions in one (updatesummary and update summary for map)?

Can we apply the same thing like reduceMap and remove first element even if it does nothing for non map element? Or just run it for map element?
</blockquote></details>

Maybe. I separated them to avoid more confusion on my side. I'll take a note and see if it can be part of another issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 438 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33SmXlb5JwDmgftmfp:-L33xiXAj5LE-spKTSs5:b4x2zt7) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L438)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Those comments are they needed?
</blockquote></details>

Not anymore. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 495 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33TYeVjEimjDVFF1bw:-L33y11WP9eP0549hPke:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L495)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space after )
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 547 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33TwVe9ZQICaHIYBnA:-L33yDWbBZxY-c79YCBe:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L547)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is commented line needed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 552 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33U2rCBdNCUbnOye3Z:-L33yFL9mg9ZZjC7BmO4:bust9av) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L552)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this function still needed?
</blockquote></details>

No. I kept it as a reference but I can throw it away. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/locales/translations.csv, line 46 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33XP5ZTb8lfubuPizK:-L33y_o5IgzY-3w1oOu7:b983rj4) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/locales/translations.csv#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why the "
</blockquote></details>

Because of the ' in d'étendues.  csv parser see it as a delimeter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/forms/ui/ui.directive.js, line 73 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Uazg96AGqJSXL-LK:-L34-NUkTUqeA0yAkjqs:b-6bbvx1) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/ui/forms/ui/ui.directive.js#L73)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do you use form[0].tabs?
</blockquote></details>

To have access to the titles

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/forms/ui/ui.directive.js, line 139 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33VVRvFCl8PphAutSe:-L341e7qj-_ZwR8u9xEK:bed0bq3) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/ui/forms/ui/ui.directive.js#L139)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You need sideMenu.logo if we look at the schema. Do you modify the schema?
</blockquote></details>

You're right it is missing. However it always creates a problem when we gather different properties under the umbrella of one of them, in this case sideMenu which have only one property.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/forms/ui/ui.directive.js, line 139 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33VVRvFCl8PphAutSe:-L342Yr3TV-prQuyGxmd:b-g8s9vy) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/ui/forms/ui/ui.directive.js#L139)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

You're right it is missing. However it always creates a problem when we gather different properties under the umbrella of one of them, in this case sideMenu which have only one property.
</blockquote></details>

Using sideMenu.logo will duplicate the entry sideMenu in the tree. I'll need to enter a supplementary key.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 545 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Tu7fi12OiCTGcrOk:-L344J0CN_w75jLZsoNT:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L545)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

es6 foor loop?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 498 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33TaZM7JQuCcger8B0:-L344LZP9XskyYeghuB_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L498)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

es6 for loop?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/modelManager.service.js, line 436 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33Sc7Cf212cwmL6QXq:-L344ORQuzyR2A1EtuZc:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/core/modelManager.service.js#L436)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You can use es6 for loop (for (let a of validArray)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/forms/ui/ui.directive.js, line 139 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-L33VVRvFCl8PphAutSe:-L34HtC89JDA21xKp3qC:b-edojm0) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/78e8140533b52499f5ca36d1e24ada4961fb0fb7/src/app/ui/forms/ui/ui.directive.js#L139)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Using sideMenu.logo will duplicate the entry sideMenu in the tree. I'll need to enter a supplementary key.
</blockquote></details>

Not elegant and a bit redundant but I can make logo appears. 
It goes like Side Menu -> Side Menu -> Show logo
However, we have string attach with how the schema is structured

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124)*

**Comment by jolevesq** [comment]
:lgtm: Good work!

---

Reviewed 3 of 22 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/124#-:-L38HzVB_MSFjK-GVTe6:b-pv0wtg)*

**Pull request merged**
