### PR TITLE
fix(plugin): Update range slider from latest and add validation to li…

### PR DESCRIPTION
**Pull request by jolevesq**
…mits plus a data picker to transform to milliseconds

Closes 552. 547

## Testing

range slider plugin
https://jolevesq.github.io/fgpa-apgf/samples/fgpv-author.html

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [ ] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/564)

### CODE REVIEW

**Comment by aparujan** [comment]
I think I am seeing an issue Johann:
I've opened the following:
https://jolevesq.github.io/fgpa-apgf/samples/fgpv-author.html
Enabled Range Slider
Click Validate
Adjust the sliders on the Range Slider
Set the interval to 3 seconds
Click Play and the slider goes immediately to the end. 

Perhaps the data set need to be changed for this demo? 

I do like the Form for the Range Slider in the Authoring Tool, however I've change the field and I am not getting the desired results from the Range Slider.

**Review by jolevesq — COMMENTED** [review]
It is for you to change the number and play with the demo. The default range and limits are 0 and 1 so there is nothing to really show. You can define your own or remove the values. Then you can play with range type, step type, date, number, precision... you may have to modify the field use if you change the type.

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/564#-:-MKAyQhT8GGLvQpe8YSF:b-hngik5)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @aparujan)

**Review by aparujan — COMMENTED** [review]
Ok just finished my tests.
 
Issues found:
1) In the Authoring Tool, placing a check mark in the Start animation on load -> doesn't seem to work as I expected
2) Placing a check mark in Play the animation in loop --> doesn't seem to loop either
 
I've test this in FireFox and Chrome.

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/564#-:-MKBZWVj0RRQJuQXe0rw:b-6piu6q)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @aparujan)

**Comment by aparujan** [comment]
___
*[src/schemas/schemaForm/plugins.en-CA.json, line 56 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/564#-MKBcNl34S6S5lRvTMyf:-MKBcNl34S6S5lRvTMyg:b-tlptj8) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/5cbef6c2d225eab10cb1db1b967a064e1ffa056e/src/schemas/schemaForm/plugins.en-CA.json#L56)):*
> ```JSON
>                                 "wmst"
>                             ],
>                             "description": "If date is selected, range and limit must be in milliseconds. Note: Date is for esri layer and WMS-T is for ogc WMS-T layer.",
> ```

"If the date is selected" <- the is missing

**Review by aparujan — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/564)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/564)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @aparujan)

___
*[src/schemas/schemaForm/plugins.en-CA.json, line 56 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/564#-MKBcNl34S6S5lRvTMyf:-MKBiV1n6iDwPy53sVoK:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/5cbef6c2d225eab10cb1db1b967a064e1ffa056e/src/schemas/schemaForm/plugins.en-CA.json#L56)):*
<details><summary><i>Previously, aparujan (Akhil Parujanwala) wrote…</i></summary><blockquote>

"If the date is selected" <- the is missing
</blockquote></details>

Done.

**Review by aparujan — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/564)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by aparujan — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/564#-:-MKBjjV63Blc9MXSH8_g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
