### PR TITLE
add(feat): merge fpga-schema-splitter

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Add schema in pieces, script and translation files at appropriate
places.
Update package.json

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/69)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[scripts/genSchemas.js, line 67 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybApqtX3tK7Dop5o2s:-KybApqtX3tK7Dop5o2t:b-it2ae7) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L67)):*
> ```JavaScript
> 
> // call our promise
> const LabelMyDef = function () {
> ```

You can use arrow function?

---

*[scripts/genSchemas.js, line 88 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybAxdM9E_NrBnOhgCY:-KybAxdM9E_NrBnOhgCZ:b-it2ae7) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L88)):*
> ```JavaScript
> 
>                     // call our promise
>                     const splitMe = function () {
> ```

You can use arrow function?

---

*[scripts/genSchemas.js, line 128 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybB2kSgI1cLZLyZOzv:-KybB2kSgI1cLZLyZOzw:b-t57ng) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L128)):*
> ```JavaScript
> 
>     // Create new definition object to be used as a non circular reference
>     $DotProp.set(schema, `definitions.circular`, {"type": "object", "properties": {"circRef": "entryGroup"}});
> ```

Single quote, spaces after { and before }

---

*[scripts/genSchemas.js, line 131 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybB0y2oq1aOhaMsjxU:-KybB0y2oq1aOhaMsjxV:b-xq462f) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L131)):*
> ```JavaScript
> 
>     // Replace circular reference with non-circular one
>     enumArray1.unshift({ "$ref": "#/definitions/circular" });
> ```

Single quote

---

*[scripts/genSchemas.js, line 136 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybBA9RbnSXl-6lAq7e:-KybBA9RbnSXl-6lAq7f:b-xq462f) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L136)):*
> ```JavaScript
>     // Replace circular reference with non-circular one
>     enumArray2.shift();
>     enumArray2.unshift({ "$ref": "#/definitions/circular" });
> ```

Single quote

---

*[scripts/genSchemas.js, line 206 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybBKfqPkEWeeJRadgl:-KybBKfqPkEWeeJRadgm:b4y6hk5) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L206)):*
> ```JavaScript
>  * @param {String} customPrefix [optional] to be added to label
>  */
> function addHelpLabel(schema, parent = '', customPrefix = '') {
> ```

This is the same function as above except ${prop}.title. Can it be one function and pass title or help as parameters. It created code climate errors.

---

*[scripts/genSchemas.js, line 247 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybBdph3EIlhzHX0zxX:-KybBdph3EIlhzHX0zxY:b4alx3k) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L247)):*
> ```JavaScript
>         // go deeper ???
>         if ($DotProp.has(schema, `${prop}.properties`)) {
>             addDefaultLabel( $DotProp.get(schema, `${prop}.properties`), `${prefix}${prop}.`);
> ```

No space after (

---

*[scripts/genSchemas.js, line 569 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybC3h2QW-nWjksrjMO:-KybC3h2QW-nWjksrjMP:b-b4y21m) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L569)):*
> ```JavaScript
> 
>     let newString = schemaString;
>     const idx = 2+2*langIdx;
> ```

spaces between + and *

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69)*

**Comment by ChrisLatRNCan** [comment]
*[scripts/genSchemas.js, line 569 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybC3h2QW-nWjksrjMO:-KybDZbSOhtZfi94gSkv:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L569)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

spaces between + and *
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69)*

**Comment by ChrisLatRNCan** [comment]
*[scripts/genSchemas.js, line 247 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybBdph3EIlhzHX0zxX:-KybDl6SBhEeawhoK3m9:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L247)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No space after (
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69)*

**Comment by ChrisLatRNCan** [comment]
*[scripts/genSchemas.js, line 206 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybBKfqPkEWeeJRadgl:-KybE1CmW-z4TVN5izc1:b-548z31) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L206)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is the same function as above except ${prop}.title. Can it be one function and pass title or help as parameters. It created code climate errors.
</blockquote></details>

Yo, I'll do a more generic function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69)*

**Comment by ChrisLatRNCan** [comment]
*[scripts/genSchemas.js, line 136 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybBA9RbnSXl-6lAq7e:-KybEHZZn8RUl-jRGJBK:b-j52ppc) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L136)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Single quote
</blockquote></details>

I need to keep them since it's litterally double quotes in the final schema

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69)*

**Comment by ChrisLatRNCan** [comment]
*[scripts/genSchemas.js, line 128 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybB2kSgI1cLZLyZOzv:-KybEpoDOHZOaFzHtlpa:b70lmxh) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L128)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Single quote, spaces after { and before }
</blockquote></details>

Here againe I need to keep them since it's litterally double quotes in the final schema

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69)*

**Comment by ChrisLatRNCan** [comment]
*[scripts/genSchemas.js, line 131 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybB0y2oq1aOhaMsjxU:-KybFLLvy_Ny-J6llqeB:b79t418) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L131)):*
> Again I need to keep them since it's litterally double quotes in the final schema

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69)*

**Comment by ChrisLatRNCan** [comment]
*[scripts/genSchemas.js, line 67 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybApqtX3tK7Dop5o2s:-KybGuhxWVWNCX0_nYwg:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L67)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You can use arrow function?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69)*

**Comment by ChrisLatRNCan** [comment]
*[scripts/genSchemas.js, line 88 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-KybAxdM9E_NrBnOhgCY:-KybGvw-wvIIXwqIm4Vg:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/e911ae4c1b464f188c244910026c79e8eedc48cd/scripts/genSchemas.js#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You can use arrow function?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/69#-:-KybNUXpafGeW-jUhAGv:bnfp4nl)*

**Pull request merged**
