### PR TITLE
doc(help): help for author in English and French

### LINKED ISSUE #272: Finish help documentation
Finish help documentation in French and English

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #272

## Description

Add help in English and French. At the same repair some bad translation along the way.

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299)

### CODE REVIEW

**Comment by ChrisLatRNCan** [comment]
Good work.

---

Reviewed 91 of 91 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/app/core/external.service.js, line 52 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIfqQQ1DgkfRku2uOS:-LAIfqQQ1DgkfRku2uOT:b-aul1yz) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/app/core/external.service.js#L52)):*
> ```JavaScript
>          * @description extension dialog controller
>          * @function extensionDialogController
>          * @param  {Object} $mdDialog Angulat mdDialog object
> ```

Angulat or Angular ?

---

*[src/locales/help/en-CA.md, line 71 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAImZjnDb8NCB1s5Bz9:-LAImZjnDb8NCB1s5BzA:bguzrl9) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/en-CA.md#L71)):*
> ```Markdown
> 
> This section is used to define the tile schemas for your viewer application. For each tile schema, a spatial reference
> systems must be defined in the _Spatial Extents Sets_ section. Again, for each tile schema, levels of detail (LODs) must
> ```

no s to system

---

*[src/locales/help/en-CA.md, line 312 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIlAQR5Wc8mY43Hrld:-LAIlAQR5Wc8mY43Hrle:bakjxhb) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/en-CA.md#L312)):*
> ```Markdown
> file by clicking the Validate button .
> 
> After a validation is executed, green check marks  will appear besides configuration
> ```

I think beside doesn't take an s

---

*[src/locales/help/en-CA.md, line 313 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIlUd57vSibBNnlDZ1:-LAIlUd57vSibBNnlDZ2:bakjxhb) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/en-CA.md#L313)):*
> ```Markdown
> 
> After a validation is executed, green check marks  will appear besides configuration
> fields that pass validation and red exclamation mark  will appear besides configuration
> ```

I think beside doesn't take an s

---

*[src/locales/help/fr-CA.md, line 4 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIqGmQB9_pSR7UgyvA:-LAIqGmQB9_pSR7UgyvB:b-wqtofv) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L4)):*
> ```Markdown
> 
> L'outil APGF (Auteur de la Plateforme géospatiale fédérale) est utilisé pour créer, mettre à jour, valider et prévisualiser
> les fichiers de configuration utilisé par la visualiseur de la Plateforme géospatiale fédérale (VPGF).
> ```

manque un 's' à utilisé

---

*[src/locales/help/fr-CA.md, line 7 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIq_5O-U9916K8Pkip:-LAIq_5O-U9916K8Pkiq:bwhvzri) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L7)):*
> ```Markdown
> 
> L'outil APGF est basé sur la bibliothèque [Angular Schema Form](https://github.com/json-schema-form/angular-schema-form).
> Cette bibliothèque permet de génèrer des formulaires à partir de schémas en format JSON en utilisant AngularJS. L'outil APGF
> ```

générer au lieu de génèrer

---

*[src/locales/help/fr-CA.md, line 11 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIqlmv2Lu6Z-3QexqL:-LAIqlmv2Lu6Z-3QexqM:b-3fzo93) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L11)):*
> ```Markdown
> fichiers de configuration. Le schéma est composé de 5 sections:
> + ** Carte **
>     + La carte est divisée en 5 sections (Étendues et niveaux de détail, Cartes de base, Couches, Légende et Composantess)
> ```

un 's' de trop à Composantes

---

*[src/locales/help/fr-CA.md, line 20 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIrDEk5rbJjNjqHc_3:-LAIrDEk5rbJjNjqHc_4:b-kpbai5) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L20)):*
> ```Markdown
> 
> Pour plus d'informations sur la structure du schéma, vous pouvez consulter le [schéma VPGF](https://github.com/fgpv-vpgf/fgpa-apgf/wiki/FGPV_schema_doc)
> dans notre page wiki. Cette section vous donnera également des informations sur les valeurs du schéma et leur effet dans le visualiseur.
> ```

Pour être constant il faudrait toujours utiliser la même expression soit visualiseur ou visualisateur. Il existe encore quelques 'visualisateur' ici et là. Les deux sont bons. Je pense que tu as mis surtout des 'visualiseur' donc ça pourrait être notre expression consacrée.

---

*[src/locales/help/fr-CA.md, line 29 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIsJen4TBbyO_TWJaD:-LAIsJen4TBbyO_TWJaE:bgbn9vy) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L29)):*
> ```Markdown
> pour développer ou réduire tous les éléments d'une section.
> 
> Certains éléments de configuration sont utiles seulement pour des utilisateurs plus avancé. Vous pouvez afficher / masquer ces éléments
> ```

avancé avec un 's'

---

*[src/locales/help/fr-CA.md, line 33 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIsRMi3Pqk1KJMr-mT:-LAIsRMi3Pqk1KJMr-mU:b-3ogyfx) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L33)):*
> ```Markdown
> 
> Certains éléments comme les cartes de base, les couches et les champs des tables de couche peuvent être réordonnés. Vous pouvez
> facilement identifier les éléments réordonnable avec le symbol de poignée . Pour réordonner
> ```

ajouter un 'e' à symbol

---

*[src/locales/help/fr-CA.md, line 89 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIt8be3Jzu0CfXIBX6:-LAIt8be3Jzu0CfXIBX7:bndqrm9) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L89)):*
> ```Markdown
> 
> Cette section est utilisée pour ajouter des cartes de base à votre application de visualisation. Pour ajouter une carte de base,
> un schéma de tuile approprié pour cette carte de basae doit déjà avoir été créé. Une fois qu'une carte de base est ajoutée,
> ```

un 'a' de trop dans bas**a**e

---

*[src/locales/help/fr-CA.md, line 184 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIu4StC6qox_BzcyLT:-LAIu4StC6qox_BzcyLU:b-wyih11) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L184)):*
> ```Markdown
> # Carte - Légende
> 
> Cette section est utilisée pour définir la légende de votre application de visualisation. Il y a 2 types de légendes à disponible:
> ```

retirer le 'à' et ajouter un 's' à disponible

---

*[src/locales/help/fr-CA.md, line 185 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIuF9OBQf2NC-CpUIu:-LAIuF9OBQf2NC-CpUIv:bll7wwv) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L185)):*
> ```Markdown
> 
> Cette section est utilisée pour définir la légende de votre application de visualisation. Il y a 2 types de légendes à disponible:
> "Autopopulate" et "Structured". La légende "Autopopulate" lit les couches telles qu'elles apparaissent dans la section Cosuches
> ```

retirer un 's' à Co**s**uches

---

*[src/locales/help/fr-CA.md, line 309 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIvMUYAFHXdOWWlG52:-LAIvMUYAFHXdOWWlG53:b-723j3w) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L309)):*
> ```Markdown
> 
> La section Liens pour les services répertorie toutes les URL des services requises par l'application de visualisation.
> Ces URL sont des valeurs en lecture seule et par conséquent ne peuvent pas être modifié. Si vous rencontrez un problème avec
> ```

ajouter 'es' à modifié

---

*[src/locales/help/fr-CA.md, line 343 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIvzipEvI3hTCcPAPG:-LAIvzipEvI3hTCcPAPH:b-8gdp0r) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L343)):*
> ```Markdown
> Vous pourrez ensuite cliquer sur ce bouton pour prévisualiser votre fichier de configuration dans une instance de l'application VPGF. Cette
> instance de prévisualisation affiche toutes les couches, cartes de base, menus et options comme ils apparaîtraient dans l'application VPGF.
> Notez que toute aide personnalisée et "À propos del a carte" de type fichier ne peuvent pas être affichées dans l'instance de prévisualisation.
> ```

'de la' au lieu de 'del a'

---

*[src/locales/help/fr-CA.md, line 353 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIwG2WDYan6X4GLJW8:-LAIwG2WDYan6X4GLJW9:b-kbt8qi) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L353)):*
> ```Markdown
> 
> Le panneau sommaire peut afficher d'autres boutons (fonctions) à côté du bouton Aperçu. Ces fonctions optionnelles sont des extensions
> à l'application APGF et pourrait ne pas être disponible pour tous les utilisateurs.
> ```

pourraient au lieu e pourrait et ajouter un 's' à disponible 

---

*[src/locales/help/info-basemaps-fr-CA.md, line 12 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIoyn_EY4sVQ5GLrHe:-LAIoyn_EY4sVQ5GLrHf:bknkbd1) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/info-basemaps-fr-CA.md#L12)):*
> ```Markdown
> 3. Liez votre carte de base avec un _Schéma de tuile_.
> 4. Ajoutez au moins une couche pour cette carte de base
>     * Entrez un Url. L'identifiant unique etle type de couche (généralement esriFeature) sont entrés automatiquement.
> ```

Espace entre 'et' et 'le'

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-:-LAIwb_Z7vl91ZF4ou1r:b-onzvup)*

**Comment by jolevesq** [comment]
Review status: 83 of 87 files reviewed at latest revision, 17 unresolved discussions.

---

*[src/locales/help/en-CA.md, line 71 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAImZjnDb8NCB1s5Bz9:-LAJ1ZP_0kkmWFFbmoAY:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/en-CA.md#L71)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

no s to system
</blockquote></details>

Done.

---

*[src/locales/help/en-CA.md, line 312 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIlAQR5Wc8mY43Hrld:-LAJ1Zpa2iht3bjxRGiC:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/en-CA.md#L312)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

I think beside doesn't take an s
</blockquote></details>

Done.

---

*[src/locales/help/en-CA.md, line 313 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIlUd57vSibBNnlDZ1:-LAJ1_EFEfARBqvYjFWP:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/en-CA.md#L313)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

I think beside doesn't take an s
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 4 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIqGmQB9_pSR7UgyvA:-LAJ1_rr5CqW4SUNaKc8:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L4)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

manque un 's' à utilisé
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 7 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIq_5O-U9916K8Pkip:-LAJ1aBmAvgWKS-UrYAn:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L7)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

générer au lieu de génèrer
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 11 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIqlmv2Lu6Z-3QexqL:-LAJ1apc78JKtHC3WaYP:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L11)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

un 's' de trop à Composantes
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 20 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIrDEk5rbJjNjqHc_3:-LAJ1jeN9PRiustsKLTw:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L20)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Pour être constant il faudrait toujours utiliser la même expression soit visualiseur ou visualisateur. Il existe encore quelques 'visualisateur' ici et là. Les deux sont bons. Je pense que tu as mis surtout des 'visualiseur' donc ça pourrait être notre expression consacrée.
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 29 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIsJen4TBbyO_TWJaD:-LAJ1ov83zBNPXBYj70v:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L29)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

avancé avec un 's'
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 33 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIsRMi3Pqk1KJMr-mT:-LAJ1t7I2Jp0dS3vJ0yO:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L33)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

ajouter un 'e' à symbol
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 89 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIt8be3Jzu0CfXIBX6:-LAJ1xJMBMAJMUekvJ7_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L89)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

un 'a' de trop dans bas**a**e
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 184 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIu4StC6qox_BzcyLT:-LAJ239v7YlLYZKuh-d-:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L184)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

retirer le 'à' et ajouter un 's' à disponible
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 185 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIuF9OBQf2NC-CpUIu:-LAJ24KJ7tn4M70ZUcll:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L185)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

retirer un 's' à Co**s**uches
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 309 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIvMUYAFHXdOWWlG52:-LAJ2LvR30MuaVx6iFPw:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L309)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

ajouter 'es' à modifié
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 343 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIvzipEvI3hTCcPAPG:-LAJ2Rwh9qjhmQ-5bzqP:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L343)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

'de la' au lieu de 'del a'
</blockquote></details>

Done.

---

*[src/locales/help/fr-CA.md, line 353 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIwG2WDYan6X4GLJW8:-LAJ2WMg7pxmZGFx476n:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L353)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

pourraient au lieu e pourrait et ajouter un 's' à disponible 
</blockquote></details>

Done.

---

*[src/locales/help/info-basemaps-fr-CA.md, line 12 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIoyn_EY4sVQ5GLrHe:-LAJ2fQDEKGfCgmCMzv1:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/info-basemaps-fr-CA.md#L12)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Espace entre 'et' et 'le'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299)*

**Comment by ChrisLatRNCan** [comment]
Ça s'en vient :smiley: 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/locales/help/fr-CA.md, line 7 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIq_5O-U9916K8Pkip:-LAJ89s37OOJc41BI471:b3p9qfu) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

L'infinitif était bien. C'est l'accent grave qui ne l'était pas. Ça prend deux accents aigus. Donc **générer**

---

*[src/locales/help/fr-CA.md, line 353 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIwG2WDYan6X4GLJW8:-LAJ8mPbCxZ2zbMorQKa:b-rorqf5) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L353)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

manque 'aient' à pourrait

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-:-LAJ96B3CN9Nktf4WsNl:b2mixev)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/locales/help/fr-CA.md, line 7 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIq_5O-U9916K8Pkip:-LAJAS9d2KrHpjCiVeoj:bfhvyw2) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L7)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

L'infinitif était bien. C'est l'accent grave qui ne l'était pas. Ça prend deux accents aigus. Donc **générer**
</blockquote></details>

Done. J'ai voulu faire ca trop vite!

---

*[src/locales/help/fr-CA.md, line 353 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299#-LAIwG2WDYan6X4GLJW8:-LAJAdf117PTBjf1d7cY:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8fd478fb0c62084b13016285cc81ec9b18037456/src/locales/help/fr-CA.md#L353)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

manque 'aient' à pourrait
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/299)*

**Pull request merged**
