### PR TITLE
Update csv

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
## Description
#44 

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/72)

### CODE REVIEW

**Comment by jolevesq** [comment]
What is package-lock file... it is more then 10000 lines of code.

---

Review status: 0 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[scripts/genSchemas.js, line 453 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-KzTws8-tcZHdS0-uVd-:-KzTws8-tcZHdS0-uVd0:blzrc4y) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/fa31496c18449605806caa8ef1b8d3204d2d4693/scripts/genSchemas.js#L453)):*
> ```JavaScript
> function saveCSV(csv, filename, schema) {
> 
>     $FS.writeFile(filename, csv, (err) => {
> ```

No () around single element

---

*[scripts/genSchemas.js, line 516 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-KzTwn9j_pZa6dUDgbzX:-KzTwn9j_pZa6dUDgbzY:blzrc4y) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/fa31496c18449605806caa8ef1b8d3204d2d4693/scripts/genSchemas.js#L516)):*
> ```JavaScript
>     const schemaString = JSON.stringify(schema, null, 2);
> 
>     $FS.writeFile(filename, schemaString, (err) => {
> ```

No () around single element

---

*[scripts/genSchemas.js, line 549 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-KzTwiSp7S6fS1k1JoQp:-KzTwiSp7S6fS1k1JoQq:blzrc4y) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/fa31496c18449605806caa8ef1b8d3204d2d4693/scripts/genSchemas.js#L549)):*
> ```JavaScript
>         const headerWr  = resolveLabels(header, csvJSON, i);
> 
>         $FS.writeFile(`${schemasDir}header.${lang[i]}.json`, headerWr, (err) => {
> ```

No () around single element

---

*[scripts/genSchemas.js, line 565 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-KzTwhcAvhVXJqZLJdjk:-KzTwhcAvhVXJqZLJdjl:blzrc4y) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/fa31496c18449605806caa8ef1b8d3204d2d4693/scripts/genSchemas.js#L565)):*
> ```JavaScript
>             const blobWr = resolveLabels(blob, csvJSON, i);
> 
>             $FS.writeFile(`${schemasDir}${prop}.${lang[i]}.json`, blobWr, (err) => {
> ```

No () around single element

---

*[scripts/genSchemas.js, line 585 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-KzTwbTZ84P3JZNS8kqi:-KzTwbT_bZRVKscGoWQK:blzrc4y) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/fa31496c18449605806caa8ef1b8d3204d2d4693/scripts/genSchemas.js#L585)):*
> ```JavaScript
>         const defRefWr = resolveLabels(defRef, csvJSON, i);
> 
>         $FS.writeFile(`${schemasDir}circular.${lang[i]}.json`, defRefWr, (err) => {
> ```

No () around single element

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-:-KzTwKvXDtub5sqbAB2h:b-9x4llu)*

**Comment by ChrisLatRNCan** [comment]
It's the new npm way of doing things with nodejs 8.9.1 LTS. I had to reinstall my tools on my workstation after HDD to SSD migration windows 10 install. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-:-KzU-1_sOodAPj5DQiwk:b-698ge6)*

**Comment by jolevesq** [comment]
I think this file is generated on install. We don't need to have it in our repo. Can you check if it can be in our .gitIgnore file

---

Review status: 0 of 16 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-:-KzU0Z19lOhGHxMaOaPc:b-rnld87)*

**Comment by ChrisLatRNCan** [comment]
Ok, I'll do

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-:-KzU0s5u7qHA8RnwDWjF:b-rlb4bs)*

**Comment by ChrisLatRNCan** [comment]
I'll do that on my machine and update the commit
npm config set package-lock false
source:
https://codeburst.io/disabling-package-lock-json-6be662f5b97d

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-:-KzU2P0FHYhPK4IUSer0:b-tg2d6n)*

**Comment by jolevesq** [comment]
Reviewed 14 of 16 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 24 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-KzUAE-K26j14UvzLQVg:-KzUAE-K26j14UvzLQVh:b8vj9rf) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/adb9532bbf42677cf44c4017f4db4f13b1258d5c/package.json#L24)):*
> ```JSON
>     "angular-translate-loader-static-files": "^2.15.1",
>     "csvtojson": "^1.1.5",
>     "daff": "^1.3.25",
> ```

I may be wrong but I think it is only needed in the second section of package. The first section is for the live and the second the build section.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72)*

**Comment by ChrisLatRNCan** [comment]
*[package.json, line 24 at r2](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-KzUAE-K26j14UvzLQVg:-KzUCBqrbo10nb-Df6Nl:bh3h8r2) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/adb9532bbf42677cf44c4017f4db4f13b1258d5c/package.json#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I may be wrong but I think it is only needed in the second section of package. The first section is for the live and the second the build section.
</blockquote></details>

I don't remember having put it in the upper part. I do the correction right now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/72#-:-KzUGldupZs0-arHVw8x:bnfp4nl)*

**Pull request merged**
