### PR TITLE
 jsdoc(layout): add miss jsdoc

### LINKED ISSUE #207: Add missing JSDOC documentation for layout

### PR DESCRIPTION
**Pull request by Pewillia**
closes #207

## Checklist

- [X] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [X] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/259)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/layout/detect-scrollbar.directive.js, line 46 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/259#-L8J9_cs-b1biiiVCSA3:-L8J9_cs-b1biiiVCSA4:bpomodm) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1d965e2c4e0d94cc6811e95c329bf1e115a05e9c/src/app/layout/detect-scrollbar.directive.js#L46)):*
> ```JavaScript
> 
> 
>     /**
> ```

Remove spaces before /**

---

*[src/app/layout/shell.directive.js, line 102 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/259#-L8JA1Jb7EjsJG3iaZDv:-L8JA1Jb7EjsJG3iaZDw:bdjdvm9) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1d965e2c4e0d94cc6811e95c329bf1e115a05e9c/src/app/layout/shell.directive.js#L102)):*
> ```JavaScript
> 
>     /**
>      * @function hideSplash
> ```

Add a description. hide Splash is use to hide the spinning wheels

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/259)*

**Comment by Pewillia** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/app/layout/shell.directive.js, line 102 at r1](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/259#-L8JA1Jb7EjsJG3iaZDv:-L8hvBVt1Fhh_4Td6_cz:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1d965e2c4e0d94cc6811e95c329bf1e115a05e9c/src/app/layout/shell.directive.js#L102)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add a description. hide Splash is use to hide the spinning wheels
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/259)*

**Comment by jolevesq** [comment]
:lgtm:

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/259#-:-L8i1qJH4Zb_ZKirhEN0:bnfp4nl)*

**Comment by jolevesq** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/259)*

**Pull request closed without merging**
