### PR TITLE
feat(form): Add map form

### LINKED ISSUE #61: Build map form
Lets build map form

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #61

## Description

Add map form. At the same time I added functions to update form, form inside index and model inside the index from model value. I also added functionalities to do Angular Schema Form. I put sample to help in futur developement

## Testing

Chrome

## Documentation

Inline

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/75)

### CODE REVIEW

**Comment by ChrisLatRNCan** [comment]
*[src/app/addon/sampleForm/sampleForm.module.js, line 13 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzYzHHh5a20FZfxR6ET:-KzYzHHh5a20FZfxR6EU:b217qnk) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/addon/sampleForm/sampleForm.module.js#L13)):*
>  remove one whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/addon/sampleSchema/sampleSchema.module.js, line 13 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzYzrTfjixPT3HEnGvV:-KzYzrTfjixPT3HEnGvW:boss3st) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/addon/sampleSchema/sampleSchema.module.js#L13)):*
> remove whitespace after comma 
,  schemaFormDecoratorsProvider

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/forms/form.service.js, line 79 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzZ-qQTEfEhNAw2R4cB:-KzZ-qQTEfEhNAw2R4cC:b-z43txi) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/ui/forms/form.service.js#L79)):*
> ```JavaScript
>     function assignForm(tree, key, value, setKey, apply) {
>         for (let obj in tree) {
>             if (!!tree[obj] && typeof(tree[obj]) === 'object') {
> ```

First time I see the not not operator ( !! ). Interesting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/forms/form.service.js, line 78 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzZ0Qcj81qlZ6LrA89_:-KzZ0Qcj81qlZ6LrA89a:b-p7xviv) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/ui/forms/form.service.js#L78)):*
> ```JavaScript
>      */
>     function assignForm(tree, key, value, setKey, apply) {
>         for (let obj in tree) {
> ```

Not better to use forEach ?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/forms/form.service.js, line 134 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzZ17WJbGHvUOQS9qsV:-KzZ17WJbGHvUOQS9qsW:bafl2mo) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/ui/forms/form.service.js#L134)):*
> ```JavaScript
>         } else {
>             // if there is key in the array of keys, walk a level deeper
>             let item = (keys.length > 0) ? findIndex(model[key], keys, value, index, returnIndexes) : model[key];
> ```

Could be **const item** instead of **let item** . Not a big deal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/forms/form.service.js, line 173 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzZ29ADKsRRRbpUBl0I:-KzZ29ADKsRRRbpUBl0J:br4rxl2) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/ui/forms/form.service.js#L173)):*
> ```JavaScript
>         for (let i = 0; i < keys.length; ++ i) {
>             // check if it is a value or index. If it is an index, parse to integer
>             let key = (isNaN(parseInt(keys[i]))) ? keys[i] : parseInt(keys[i]);
> ```

Could be **const key** instead of **let key**

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75)*

**Comment by jolevesq** [comment]
Review status: 0 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/addon/sampleForm/sampleForm.module.js, line 13 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzYzHHh5a20FZfxR6ET:-KzZ3Yyrtdh9rMwH9g_p:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/addon/sampleForm/sampleForm.module.js#L13)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

>  remove one whitespace
</blockquote></details>

Done.

---

*[src/app/addon/sampleSchema/sampleSchema.module.js, line 13 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzYzrTfjixPT3HEnGvV:-KzZ3_SP7uCr9y8sZvhv:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/addon/sampleSchema/sampleSchema.module.js#L13)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

> remove whitespace after comma 
,  schemaFormDecoratorsProvider

</blockquote></details>

Done.

---

*[src/app/ui/forms/form.service.js, line 78 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzZ0Qcj81qlZ6LrA89_:-KzZ3aVE1VXQRSeRIPeS:b-tvm8ls) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/ui/forms/form.service.js#L78)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Not better to use forEach ?  
</blockquote></details>

IT is the ES6 way of doing it (http://www.benmvp.com/learning-es6-for-of-loop/). The forEach was the ES5 

---

*[src/app/ui/forms/form.service.js, line 134 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzZ17WJbGHvUOQS9qsV:-KzZ5exfolodLpXEOgtW:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/ui/forms/form.service.js#L134)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Could be **const item** instead of **let item** . Not a big deal.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75)*

**Comment by jolevesq** [comment]
Review status: 0 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/ui/forms/form.service.js, line 173 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-KzZ29ADKsRRRbpUBl0I:-KzZ5gtHeiyAuC_92aOy:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/c7adfc5c34f16dd5f335e7fefb69e3649336c619/src/app/ui/forms/form.service.js#L173)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Could be **const key** instead of **let key**
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75)*

**Comment by ChrisLatRNCan** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75#-:-KzZDHizfQnwcw9DhRGE:bnfp4nl)*

**Comment by ChrisLatRNCan** [comment]
Reviewed 20 of 20 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/75)*

**Pull request merged**
