### PR TITLE
feat(form): Add automatique lods population from service

### LINKED ISSUE #174: Get lods from services
Do the same as for the fields. Do not let user enter manually the lods. Grab them from a service.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #174

## Testing

Chrome

## Documentation

Inline

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/193)

### CODE REVIEW

**Comment by ChrisLatRNCan** [comment]
Is it possible not to go back at the top of the page when the url window appears so we don't have to scroll back down to see i the new lods are loaded ?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/193#-:-L5jQkiPzVIxWp9IHtZs:b-8491gr)*

**Comment by jolevesq** [comment]
Good idea, I will do it.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/193#-:-L5jTHO31o99NiUGOAbv:b-1bss5g)*

**Comment by jolevesq** [comment]
Done! Modified the behaviour for all other mdDialog

---

Review status: 7 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/193#-:-L5jlLKM_591ij-VkrwA:b-lsvse0)*

**Comment by ChrisLatRNCan** [comment]
:lgtm:

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/193#-:-L5nUdxzE6Z2L_w9MuTF:bnfp4nl)*

**Comment by ChrisLatRNCan** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/193)*

**Pull request merged**
