### PR TITLE
add(feature): link preview, expand and collapse buttons with validation

### LINKED ISSUE #166: Link Preview with validation
We want the Preview button to be available only when there's no more error after running the validation process. So, by default the button is disabled until the validation process has been executed and no more error has been identified.  Also, had content to config-AuthorA so the validation process will execute without error (demo purpose).

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Before:
- Preview button is enabled even if there is still validation errors
- Expand and collapse are enabled even before validation tree creation
- There is no about section in config-authorA
After:
- Preview button is disabled until there is no more validation error
- Expand and collapse are disabled until validation tree creation
- There is an about section in config-authorA

Closes #166

## Testing
Test with Chrome and Fox

## Checklist

- [ ] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] ~~Release notes have been updated~~
- [ ] PR targets the correct release version
- [x] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/186)

### CODE REVIEW

**Comment by jolevesq** [comment]
In French, expand and collapse are not disable when I switch language. Still enable when I switch back to English.

If I remove ID to extent it create an error but when I hit validate there is no error in the tree and preview is still enable

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/186#-:-L5F1zgAFsvEFvT66itl:bhj26v6)*

**Comment by ChrisLatRNCan** [comment]
good catch

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/186#-:-L5F4OhYFc29Hoserm9c:bd30ifx)*

**Comment by jolevesq** [comment]
I still have: remove ID to extent it create an error but when I hit validate there is no error in the tree and preview is still enable.

expand and collapse are good

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/186#-:-L5Fa0FSAuLwHv2rwy8c:b-s2ta1t)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/186#-:-L5KeaxSmMu-vcyJnzDc:bnfp4nl)*

**Pull request merged**
