### PR TITLE
add(doc): weekly update May 7th 2018

### LINKED ISSUE #332: Weekly Doc review May 7th 2018
- Add baseMap Node JSON tree
- Add part of layers Node JSON tree
- Remove duplicate hyperlinks and keep just one at bottom of the object's attributes list
- add dividers `***`
- Divide DOC in multiple files
- Create menu and pages corresponding to schema sections

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
- Add baseMap Node JSON tree
- Add part of layers Node JSON tree
- Remove duplicate hyperlinks and keep just one at bottom of the object's attributes list
- add dividers `***`
- Divide DOC in multiple files
- Create menu and pages corresponding to schema sections

Closes #332

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/333)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[wiki/schema-language.en-CA.md, line 11 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/333#-LBzaoOXAfX1_YUIc7ZK:-LBzaoOYAcgqkWCTOk-m:b1994lc) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cc1825f02cc381fe363e15630a57ee139bd1ce0/wiki/schema-language.en-CA.md#L11)):*
> ```Markdown
> 
> ```js
> "language": "en"
> ```

Needs to be en-CA or fr-CA

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/333)*

**Comment by ChrisLatRNCan** [comment]
*[wiki/schema-language.en-CA.md, line 11 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/333#-LBzaoOXAfX1_YUIc7ZK:-LBzfOhD2szqTvnSiT6Q:b-w76tih) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cc1825f02cc381fe363e15630a57ee139bd1ce0/wiki/schema-language.en-CA.md#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Needs to be en-CA or fr-CA
</blockquote></details>

That's an example. Maybe I should put example just over it

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/333)*

**Comment by jolevesq** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wiki/schema-language.en-CA.md, line 11 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/333#-LBzaoOXAfX1_YUIc7ZK:-LBzi84jAKjVLChAzils:b-8nrbgn) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cc1825f02cc381fe363e15630a57ee139bd1ce0/wiki/schema-language.en-CA.md#L11)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

That's an example. Maybe I should put example just over it
</blockquote></details>

I think you should put the real info. en for language will never work

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/333)*

**Comment by ChrisLatRNCan** [comment]
*[wiki/schema-language.en-CA.md, line 11 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/333#-LBzaoOXAfX1_YUIc7ZK:-LBzj1Y18_uPx6kf8ziS:bwxfcfb) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8cc1825f02cc381fe363e15630a57ee139bd1ce0/wiki/schema-language.en-CA.md#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think you should put the real info. en for language will never work
</blockquote></details>

:grin: ok

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/333)*

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/333#-:-LBzt77d3gh9FDj7g2TY:bnfp4nl)*

**Pull request merged**
