### PR TITLE
fix(extent): Specify extent for every extentset to avoid bad projection

### LINKED ISSUE #288: Set default/full/maximum extent by extent set
Currently we reproject the extent from the choosen projection to the other. Because we reproject a bounding box, it creates bad values. We need to be able to set the extent for each projection.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #288

## Testing

Chrome with a new extent set not 3978, 3857 or 102100

## Documentation

Updated help section for extentset and lod

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361)

### CODE REVIEW

**Comment by ChrisLatRNCan** [comment]
If I had a unknown WKID would it be possible to have an error message ?



---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361#-:-LDqP5bj3N-DQasU5JU5:bwm1s0b)*

**Comment by jolevesq** [comment]
No because there is thousand of wkid. We can do this only if we put a drop down menu of supported wkid

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361#-:-LDqQahV9wsbj5BP4Ddx:b-67wrco)*

**Comment by ChrisLatRNCan** [comment]
so could you put a dropdown or wait for a next issue ?

---







*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361#-:-LDqRUfpBUDs95Wg7XMA:bndugvj)*

**Comment by jolevesq** [comment]
Yep but yesterday we agreed for no dropdown solution. What do you prefer...

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361#-:-LDqWCFiB76-IQ7uRELN:bayvp4u)*

**Comment by ChrisLatRNCan** [comment]
Review status: 14 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/app/ui/forms/map/map.directive.js, line 626 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361#-LDqb-J55J3Pepw2qibK:-LDqb-J6-kyfG7obgiGE:bktap7o) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/6a55d22149ebd9eef17c1081b66caa36a90a5247/src/app/ui/forms/map/map.directive.js#L626)):*
> ```JavaScript
>                                     { 'type': 'section', 'htmlClass': 'col-xs-2', 'items': [
>                                         { 'key': 'extentSets[].spatialReference.wkid', 'htmlClass': 'av-extentset-wkid', 'onChange': debounceService.registerDebounce(model => {
>                                             const buttons = document.activeElement.parentElement.parentElement.parentElement.parentElement.getElementsByTagName('button');
> ```

Is there a more direct way to get to the point ? parentElement.parentElement.parentElement.parentElement seems a lot.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361)*

**Comment by jolevesq** [comment]
Review status: 14 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/forms/map/map.directive.js, line 626 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361#-LDqb-J55J3Pepw2qibK:-LDqjHKG9lxuiG7qYmOw:b-x1c0g7) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/6a55d22149ebd9eef17c1081b66caa36a90a5247/src/app/ui/forms/map/map.directive.js#L626)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Is there a more direct way to get to the point ? parentElement.parentElement.parentElement.parentElement seems a lot.
</blockquote></details>

There is always a more direct way :smiley: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361)*

**Comment by jolevesq** [comment]
Review status: 14 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/app/ui/forms/map/map.directive.js, line 626 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361#-LDqb-J55J3Pepw2qibK:-LDqjRRI13NEaJnB2z85:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/6a55d22149ebd9eef17c1081b66caa36a90a5247/src/app/ui/forms/map/map.directive.js#L626)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is always a more direct way :smiley: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361)*

**Comment by ChrisLatRNCan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361#-:-LDqkMlU8iKDcr4Btj37:bnfp4nl)*

**Comment by ChrisLatRNCan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/361)*

**Pull request merged**
