### PR TITLE
feat(legend): Add text input to write legend in JSON

### LINKED ISSUE #133: Add text section to legend to write json
We don't expect to have full legend support until end of March. In the mean time it would be useful to have a input text area so user can write the legend section without going out of the viewer.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #133

## Testing

Chrome

## Documentation

Inline

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/137)

### CODE REVIEW

**Comment by ChrisLatRNCan** [comment]
*[src/schemas/schemaForm/map.en-CA.json, line 1118 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/137#-L39JCdfUNuUpVGh0hZd:-L39JCdgJsdp3VfdIoGL:b-o4fkfo) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8a4fa4178cca19f09da186c73526688e6497b731/src/schemas/schemaForm/map.en-CA.json#L1118)):*
> ```JSON
>                     "default": "autopopulate"
>                 },
>                 "root": {
> ```

Do we need a title attribute ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/137)*

**Comment by ChrisLatRNCan** [comment]
*[src/schemas/schemaForm/map.fr-CA.json, line 1118 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/137#-L39JJIi76451kzyYwKy:-L39JJIi76451kzyYwKz:b-o4fkfo) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8a4fa4178cca19f09da186c73526688e6497b731/src/schemas/schemaForm/map.fr-CA.json#L1118)):*
> ```JSON
>                     "default": "autopopulate"
>                 },
>                 "root": {
> ```

Do we need a title attribute ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/137)*

**Comment by jolevesq** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/schemas/schemaForm/map.en-CA.json, line 1118 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/137#-L39JCdfUNuUpVGh0hZd:-L39MahNMZbHhXjyW8H5:bps2kxy) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8a4fa4178cca19f09da186c73526688e6497b731/src/schemas/schemaForm/map.en-CA.json#L1118)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Do we need a title attribute ?
</blockquote></details>

No because I put a title on the fieldset. I even set notitle on root. 

---

*[src/schemas/schemaForm/map.fr-CA.json, line 1118 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/137#-L39JJIi76451kzyYwKy:-L39MtuOgBcGBa24Bh4X:b-rm7f3g) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/8a4fa4178cca19f09da186c73526688e6497b731/src/schemas/schemaForm/map.fr-CA.json#L1118)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

Do we need a title attribute ?
</blockquote></details>

No because I put a title on the fieldset. I even set notitle on root

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/137)*

**Comment by ChrisLatRNCan** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/137)*

**Pull request merged**
