### PR TITLE
add(header): add schema version management

### LINKED ISSUE #73: Manage schema's versions
Actually, we always work with the latest version of the viewer schema. As time goes by, other versions of it may appear. We need to develop a version managing process so user could edit/create config files corresponding to a particular version of the viewer/schema.

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
-Update schemas
-Update forms
-Erase unused files

Closes #73, #77

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [ ] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/342)

### CODE REVIEW

**Comment by jolevesq** [comment]
Reviewed 33 of 35 files at r1.
Review status: 32 of 33 files reviewed at latest revision, all discussions resolved.

---

*[src/app/core/modelManager.service.js, line 241 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/342#-LDC1lbM786E9xRlErCN:-LDC1lbNEPoJfN0Lm1To:b-oemh9f) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/568f9bec92e3783a928d1cbe447d689d8fab893f/src/app/core/modelManager.service.js#L241)):*
> ```JavaScript
>         }
> 
>         if (model === undefined) {
> ```

Do it as just one return true and one return false

---

*[src/schemas/schemaForm/map.en-CA.json, line 338 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/342#-LDC2dxc4TK9LN7bPx1H:-LDC2dxc4TK9LN7bPx1I:brjbwqx) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/568f9bec92e3783a928d1cbe447d689d8fab893f/src/schemas/schemaForm/map.en-CA.json#L338)):*
> ```JSON
>                     "type": "object",
>                     "title": "North arrow",
>                     "version": "2.3",
> ```

Why did you add version in schema?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/342)*

**Comment by jolevesq** [comment]
Reviewed 1 of 35 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/app/core/modelManager.service.js, line 235 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/342#-LDC34BX7nzOj1jxUNcT:-LDC34BX7nzOj1jxUNcU:by64urd) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/568f9bec92e3783a928d1cbe447d689d8fab893f/src/app/core/modelManager.service.js#L235)):*
> ```JavaScript
>     function checkVersion(type = 'dev') {
>         const model = _model['version'];
>         let version = constants.devVersion;
> ```

Do ternaty instead of setting here and doing a if prod after

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/342)*

**Comment by ChrisLatRNCan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/app/core/modelManager.service.js, line 235 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/342#-LDC34BX7nzOj1jxUNcT:-LDHIbFy6ajMpBnSXqur:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/568f9bec92e3783a928d1cbe447d689d8fab893f/src/app/core/modelManager.service.js#L235)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do ternaty instead of setting here and doing a if prod after
</blockquote></details>

Done.

---

*[src/schemas/schemaForm/map.en-CA.json, line 338 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/342#-LDC2dxc4TK9LN7bPx1H:-LDHDhOoALbsgg9ts9qG:b-pb0o5) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/568f9bec92e3783a928d1cbe447d689d8fab893f/src/schemas/schemaForm/map.en-CA.json#L338)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why did you add version in schema?
</blockquote></details>

To easily spot the changes in the schemas. In the next version I'll remove them and put "version": "2.4" where the changes will happen.
I don't think there's an impact on the author as long as it is outside properties.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/342)*

**Comment by jolevesq** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/342)*

**Pull request merged**
