### PR TITLE
feat(ddr): Link authoring tool to DDR

### LINKED ISSUE #159: Create page (extension) to link to DDR
Add the interface to link to DDR inside the fgpa repo as an extension.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #159

## Description

We can now send file to DDR from the authoring tool with this extension

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/169)

### CODE REVIEW

**Comment by ChrisLatRNCan** [comment]
Can you add a comment to #166 so DDR button would have the same treatment as PREVIEW.
However, since it is an extension, should DDR button enabling/disabling should be done at extension level or author level ? 
I don't pretend understanding everything but it :lgtm: 

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/169#-:-L4aoJECGvmbIIXOBnxL:bj0zs75)*

**Comment by jolevesq** [comment]
It is not for the active config file, it is for a zip package to upload. Maybe summary panel is not where we should put it. I am open to suggestions.  The button should always be enable if the extension is there. We can maybe add information inside the panel to let user know they need to have a zip file with ... format. I can modify some tiny thing before I push again. Wait until bofore merging. I will try to fix why it doesn't work on IE

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/169#-:-L4atQdt7OtWkoHPQJ9Q:b-hfnl4c)*

**Comment by jolevesq** [comment]
Will not work with IE because eval() doean't work and execScript has been depricated.

---

Review status: 9 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/169#-:-L4blBE1ThCz0c-CqFz8:bvl7xvz)*

**Comment by ChrisLatRNCan** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/169#-:-L4fKbyAToCPFyaW1-g3:bnfp4nl)*

**Comment by ChrisLatRNCan** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/169)*

**Pull request merged**
