### PR TITLE
add(doc): weekly doc update June 4th-8th

### LINKED ISSUE #371: Weekly doc June 4th-8th
Add table node in schema documentation for wiki

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
add table node to schema doc in wiki

Closes #371

## Documentation
Wiki update

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [x] Release notes have been updated
- [x] PR targets the correct release version
- [x] Help files and documentation have been updated

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/372)

### CODE REVIEW

**Comment by jolevesq** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @ChrisLatRNCan)

---

*[wiki/schema-map.en-CA.md, line 1208 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/372#-LEjlQ4eC1jKpDN362Wc:-LEjlQ4eC1jKpDN362Wd:bi2y1n1) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/9b704e89c5444fc9c3a7b18f27a27fc8a411933f/wiki/schema-map.en-CA.md#L1208)):*
> ```Markdown
> 
> >### [node:_**`columnNode`**_](#node--columnnode)
> >>Specifies the field name (data) to use to link to the layer column. Must exist in the layer.
> ```

Same line below... is it normal?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/372#-:-LEjlkR3-a_qzy9wjoLd:bnfp4nl)*

**Comment by ChrisLatRNCan** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @ChrisLatRNCan)

---

*[wiki/schema-map.en-CA.md, line 1208 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/372#-LEjlQ4eC1jKpDN362Wc:-LEjmuViEOLNMlnrWArL:bg2k6xe) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/9b704e89c5444fc9c3a7b18f27a27fc8a411933f/wiki/schema-map.en-CA.md#L1208)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same line below... is it normal?
</blockquote></details>

No. I do the fix. Thx

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/372)*

**Comment by ChrisLatRNCan** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

---

*[wiki/schema-map.en-CA.md, line 1208 at r1](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/372#-LEjlQ4eC1jKpDN362Wc:-LEjnL2T64YCwptELVde:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/9b704e89c5444fc9c3a7b18f27a27fc8a411933f/wiki/schema-map.en-CA.md#L1208)):*
<details><summary><i>Previously, ChrisLatRNCan (Christian Latouche) wrote…</i></summary><blockquote>

No. I do the fix. Thx
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/372)*

**Comment by jolevesq** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/372#-:-LEjnTX46XWsMAjOGn3E:bnfp4nl)*

**Pull request merged**
