### PR TITLE
add(core): consolidate validity

### LINKED ISSUE #139: Summary doesnt update when lods is deleted
When we delete one of the lods, a validation error occurs inside tile schema because lods id is missing. When we hit validate, the summary panel doesn't reflect the problem!

### PR DESCRIPTION
**Pull request by ChrisLatRNCan**
Before:
-Missing validation on undefined items
-Missing validation icons for layers, basemaps, tileSchemas, extents and lods
After:
-Add global validation function to be used by PREVIEW
-Add validation of undefined elements
-Add validation icon for layers, basemaps, tileSchemas, extents and lods

Closes #139,#142,#151

## Testing
Chrome

## Checklist

- [x] Commit messages follow [the guidelines](https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/CONTRIBUTING.md#-git-commit-guidelines)
- [ ] ~~Release notes have been updated~~
- [x] PR targets the correct release version
- [ ] ~~Help files and documentation have been updated~~

Remember, it is a *muffin offence* to open a PR with any of the above checklist items incomplete.

Please keep the original issue up to date with the final solution, expected behaviour, and any additional notes for testers

---
This change is [Reviewable](https://reviewable.io/reviews/fgpv-vpgf/fgpa-apgf/165)

### CODE REVIEW

**Comment by jolevesq** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/app/core/common.service.js, line 75 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I23CqnK6I_iAPOJ5O:-L4I23CqnK6I_iAPOJ5P:b5szsd5) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/core/common.service.js#L75)):*
> ```JavaScript
>         let typeObject = '';
> 
>         if (Array.isArray(obj)){
> ```

Space before {

---

*[src/app/core/common.service.js, line 77 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I25wyPrhUW-MZw70J:-L4I25wyPrhUW-MZw70K:b-29ij29) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/core/common.service.js#L77)):*
> ```JavaScript
>         if (Array.isArray(obj)){
>             typeObject = 'array';
>         } else if (obj === null){
> ```

I think (don't remember where I read this) it is better to use typeof to compare instead of null value. Space before {

---

*[src/app/core/stateManager.service.js, line 180 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I2YUtnc9e1jWyruCR:-L4I2YUtnc9e1jWyruCS:b2gxe2k) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/core/stateManager.service.js#L180)):*
> ```JavaScript
>         const target = path.shift();
>         if (path.length > 0) {
>             // Fin proper target place
> ```

Typo, miss a d to find

---

*[src/app/core/stateManager.service.js, line 187 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I2iG031sLQeRT_Zq4:-L4I2iG031sLQeRT_Zq5:b-wmhf08) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/core/stateManager.service.js#L187)):*
> ```JavaScript
> 
>                 if (isNumber && j === parseInt(target)) {
>                     setStateValueUp(stateModel.items[j], path, param, value);
> ```

Looks like it calls the same function as below. Do I miss something

---

*[src/app/core/stateManager.service.js, line 224 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I2x5WEc_er7rUtdRu:-L4I2x5WEc_er7rUtdRv:b-m9jxou) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/core/stateManager.service.js#L224)):*
> ```JavaScript
>     /**
>      * Set undefined parameter in state model and update
>      * validit of upper hierarchy
> ```

Typo, miss y

---

*[src/app/ui/forms/version/version.directive.js, line 74 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I3BEoUBlOSKdbpmfM:-L4I3BEpOW8nUloRG6Ia:b-od88ul) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/ui/forms/version/version.directive.js#L74)):*
> ```JavaScript
>         $scope.$broadcast('schemaFormValidate');
>         // There's no tab just the form
>         stateManager.validateModel(self.modelName, $scope.activeForm, $scope.form, $scope.model);
> ```

There is no modification for map.directive?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/common.service.js, line 75 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I23CqnK6I_iAPOJ5O:-L4I3kog45x0XLK3wZn_:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/core/common.service.js#L75)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space before {
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/common.service.js, line 77 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I25wyPrhUW-MZw70J:-L4I3zLo-Z9S0u8_BjjC:br8mg48) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/core/common.service.js#L77)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think (don't remember where I read this) it is better to use typeof to compare instead of null value. Space before {
</blockquote></details>

null is identified as a object by typeof https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Op%C3%A9rateurs/L_op%C3%A9rateur_typeof
Done for the space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/stateManager.service.js, line 180 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I2YUtnc9e1jWyruCR:-L4I4_2231OozgXIpE76:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/core/stateManager.service.js#L180)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo, miss a d to find
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/stateManager.service.js, line 224 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I2x5WEc_er7rUtdRu:-L4I4jPegg4r9l2FWOF7:b-896fix) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/core/stateManager.service.js#L224)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo, miss y
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165)*

**Comment by jolevesq** [comment]
Should preview only be enable when shcema is valid?

---

Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-:-L4I4u9x4inOj5aoOJIO:b-b7dxyi)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/ui/forms/version/version.directive.js, line 74 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I3BEoUBlOSKdbpmfM:-L4I4nfnEdlxa8shDFCN:b8mgpx3) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/ui/forms/version/version.directive.js#L74)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is no modification for map.directive?
</blockquote></details>

It was already changed in the previous PR because I needed the model to get layers et basemaps names. In that time it was not mandatory for the other sections.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165)*

**Comment by ChrisLatRNCan** [comment]
*[src/app/core/stateManager.service.js, line 187 at r1](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-L4I2iG031sLQeRT_Zq4:-L4I6H_cMNi9BTJ1p33i:b-jecew) ([raw file](https://github.com/fgpv-vpgf/fgpa-apgf/blob/1b0a639fc65e2016beb42bd5250593633250efb4/src/app/core/stateManager.service.js#L187)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Looks like it calls the same function as below. Do I miss something
</blockquote></details>

The test is different. But it call exactly the same function with same parameters. I can do a OR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165)*

**Comment by ChrisLatRNCan** [comment]
Probably yes but it is not covered by #151. So, I'll create another issue for Preview behaviour.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-:-L4I6uv8vleYiqIrwqwY:b-8uffil)*

**Comment by jolevesq** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165#-:-L4LX1f-BOaRi0X9sNWr:bnfp4nl)*

**Comment by jolevesq** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fgpv-vpgf/fgpa-apgf/165)*

**Pull request merged**
